# 선형 회귀

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
torch.manual_seed(1)

In [3]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [4]:
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [5]:
print(y_train)
print(y_train.shape)

tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


In [6]:
W = torch.zeros(1, requires_grad=True) # 가중치 W를 0으로 초기화하고 학습을 통해 값이 변경되는 변수임을 명시함
# requires_grad = True : 학습을 통해 계속 값이 변경되는 변수임을 의미

print(W)

tensor([0.], requires_grad=True)


In [7]:
b = torch.zeros(1, requires_grad=True)

print(b)

tensor([0.], requires_grad=True)


In [10]:
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [11]:
# 비용 함수 선언하기
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [12]:
# 경사하강법 구현하기
optimizer = optim.SGD([W, b], lr = 0.01)

In [13]:
# gradient를 0으로 초기화
optimizer.zero_grad()

# 비용 함수를 미분하여 gradient 계산
cost.backward()

# W와 b를 업데이트
optimizer.step()


In [16]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

# 모델 초기화
W = torch.zeros(1, requires_grad = True)
b = torch.zeros(1, requires_grad = True)

# optimizer 설정
optimizer = optim.SGD([W, b], lr = 0.01)

nb_epochs = 1999 # 원하는 만큼 경사 하강법을 반복

for epoch in range(nb_epochs + 1) :
    
    # H(x) 계산 
    hypothesis = x_train * W + b
    
    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)
    
    # cost로 H(x)계산
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    # 100번마다 로그 출력
    if epoch % 100 == 0 :
        print('Epoch {:4d}/{} \t W: {:.3f} \t b: {:.3f} \t Cost: {:.6f}'.format(epoch, nb_epochs, W.item(), b.item(), cost.item()))

Epoch    0/1999 	 W: 0.187 	 b: 0.080 	 Cost: 18.666666
Epoch  100/1999 	 W: 1.746 	 b: 0.578 	 Cost: 0.048171
Epoch  200/1999 	 W: 1.800 	 b: 0.454 	 Cost: 0.029767
Epoch  300/1999 	 W: 1.843 	 b: 0.357 	 Cost: 0.018394
Epoch  400/1999 	 W: 1.876 	 b: 0.281 	 Cost: 0.011366
Epoch  500/1999 	 W: 1.903 	 b: 0.221 	 Cost: 0.007024
Epoch  600/1999 	 W: 1.924 	 b: 0.174 	 Cost: 0.004340
Epoch  700/1999 	 W: 1.940 	 b: 0.136 	 Cost: 0.002682
Epoch  800/1999 	 W: 1.953 	 b: 0.107 	 Cost: 0.001657
Epoch  900/1999 	 W: 1.963 	 b: 0.084 	 Cost: 0.001024
Epoch 1000/1999 	 W: 1.971 	 b: 0.066 	 Cost: 0.000633
Epoch 1100/1999 	 W: 1.977 	 b: 0.052 	 Cost: 0.000391
Epoch 1200/1999 	 W: 1.982 	 b: 0.041 	 Cost: 0.000242
Epoch 1300/1999 	 W: 1.986 	 b: 0.032 	 Cost: 0.000149
Epoch 1400/1999 	 W: 1.989 	 b: 0.025 	 Cost: 0.000092
Epoch 1500/1999 	 W: 1.991 	 b: 0.020 	 Cost: 0.000057
Epoch 1600/1999 	 W: 1.993 	 b: 0.016 	 Cost: 0.000035
Epoch 1700/1999 	 W: 1.995 	 b: 0.012 	 Cost: 0.000022
Epoch 180

In [18]:
# optimizer.zero_grad()가 필요한 이유

import torch
w = torch.tensor(2.0, requires_grad = True)

nb_epochs = 20
for epoch in range(nb_epochs + 1) :
    
    z = 2*w
    
    z.backward()
    print('수식을 w로 미분한 값 : {}'.format(w.grad))
    
# 계속해서 미분값인 2가 누적됨 > optimizer.zero_grad()를 통해 미분값을 계속 0으로 초기화 시켜줘야함

수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 4.0
수식을 w로 미분한 값 : 6.0
수식을 w로 미분한 값 : 8.0
수식을 w로 미분한 값 : 10.0
수식을 w로 미분한 값 : 12.0
수식을 w로 미분한 값 : 14.0
수식을 w로 미분한 값 : 16.0
수식을 w로 미분한 값 : 18.0
수식을 w로 미분한 값 : 20.0
수식을 w로 미분한 값 : 22.0
수식을 w로 미분한 값 : 24.0
수식을 w로 미분한 값 : 26.0
수식을 w로 미분한 값 : 28.0
수식을 w로 미분한 값 : 30.0
수식을 w로 미분한 값 : 32.0
수식을 w로 미분한 값 : 34.0
수식을 w로 미분한 값 : 36.0
수식을 w로 미분한 값 : 38.0
수식을 w로 미분한 값 : 40.0
수식을 w로 미분한 값 : 42.0


In [21]:
# torch.manual_seed()를 하는 이유

import torch

torch.manual_seed(3)

print('랜덤 시드가 3일 때')
for i in range(1, 3) :
    print(torch.rand(1))

랜덤 시드가 3일 때
tensor([0.0043])
tensor([0.1056])


In [22]:
torch.manual_seed(5)
print('랜덤 시드가 5일 때')
for i in range(1,3) :
    print(torch.rand(1))

랜덤 시드가 5일 때
tensor([0.8303])
tensor([0.1261])


In [23]:
torch.manual_seed(3)

print('랜덤 시드가 3일 때')
for i in range(1, 3) :
    print(torch.rand(1))

랜덤 시드가 3일 때
tensor([0.0043])
tensor([0.1056])


# 자동 미분

In [24]:
import torch

In [25]:
w = torch.tensor(2.0, requires_grad=True)

y = w**2
z = 2*y + 5

In [26]:
z.backward()

In [27]:
print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 8.0


# 다중 선형 회귀(Multivariable Linear regression)

In [28]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [29]:
torch.manual_seed(1)

In [30]:
# 훈련 데이터
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [32]:
# 가중치 w와 편향 b 초기화
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [34]:
# optimizer 설정
optimizer = optim.SGD([w1, w2, w3, b], lr = 1e-5)

nb_epochs = 1000
for epoch in range(nb_epochs + 1) :
    
    # H(x) 계산
    hypothesis = x1_train * w1 + x2_train * w2 + x3_train * w3 + b
    
    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)
    
    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    # 100번마다 로그 출력
    if epoch % 100 == 0 :
        print('Epoch {:4d}/{} \t w1: {:.3f} \t w2: {:.3f} \t w3: {:.3f} \t b: {:.3f} \t Cost: {:.6f}'.format(epoch, nb_epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item()))
        

Epoch    0/1000 	 w1: 0.718 	 w2: 0.612 	 w3: 0.680 	 b: 0.009 	 Cost: 1.078961
Epoch  100/1000 	 w1: 0.722 	 w2: 0.608 	 w3: 0.680 	 b: 0.009 	 Cost: 1.038184
Epoch  200/1000 	 w1: 0.727 	 w2: 0.603 	 w3: 0.681 	 b: 0.010 	 Cost: 0.999508
Epoch  300/1000 	 w1: 0.731 	 w2: 0.599 	 w3: 0.681 	 b: 0.010 	 Cost: 0.962850
Epoch  400/1000 	 w1: 0.735 	 w2: 0.595 	 w3: 0.681 	 b: 0.010 	 Cost: 0.928104
Epoch  500/1000 	 w1: 0.739 	 w2: 0.590 	 w3: 0.681 	 b: 0.010 	 Cost: 0.895127
Epoch  600/1000 	 w1: 0.743 	 w2: 0.586 	 w3: 0.682 	 b: 0.010 	 Cost: 0.863870
Epoch  700/1000 	 w1: 0.746 	 w2: 0.582 	 w3: 0.682 	 b: 0.010 	 Cost: 0.834205
Epoch  800/1000 	 w1: 0.750 	 w2: 0.579 	 w3: 0.682 	 b: 0.010 	 Cost: 0.806107
Epoch  900/1000 	 w1: 0.754 	 w2: 0.575 	 w3: 0.682 	 b: 0.010 	 Cost: 0.779432
Epoch 1000/1000 	 w1: 0.757 	 w2: 0.571 	 w3: 0.682 	 b: 0.011 	 Cost: 0.754143


In [35]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [38]:
print(x_train.shape)
print(y_train.shape)

torch.Size([5, 3])
torch.Size([5, 1])


In [39]:
W = torch.zeros((3,1), requires_grad = True)
b = torch.zeros(1, requires_grad=True)

In [40]:
hypothesis = x_train.matmul(W) + b

In [41]:
# 모델 초기화
W = torch.zeros((3,1), requires_grad = True)
b = torch.zeros(1, requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([W, b], lr = 1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1) :
    
    # H(x) 계산
    # 편향 b는 브로드 캐스팅되어 각 샘플에 더해진다.
    hypothesis = x_train.matmul(W) + b
    
    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)
    
    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    print('Epoch {:4d}/{} \t hypothesis: {} \t Cost: {:.6f}'.format(epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()))

Epoch    0/20 	 hypothesis: tensor([0., 0., 0., 0., 0.]) 	 Cost: 29661.800781
Epoch    1/20 	 hypothesis: tensor([66.7178, 80.1701, 76.1025, 86.0194, 61.1565]) 	 Cost: 9537.694336
Epoch    2/20 	 hypothesis: tensor([104.5421, 125.6208, 119.2478, 134.7862,  95.8280]) 	 Cost: 3069.590088
Epoch    3/20 	 hypothesis: tensor([125.9858, 151.3882, 143.7087, 162.4333, 115.4844]) 	 Cost: 990.670898
Epoch    4/20 	 hypothesis: tensor([138.1429, 165.9963, 157.5768, 178.1071, 126.6283]) 	 Cost: 322.482086
Epoch    5/20 	 hypothesis: tensor([145.0350, 174.2780, 165.4395, 186.9928, 132.9461]) 	 Cost: 107.717064
Epoch    6/20 	 hypothesis: tensor([148.9423, 178.9730, 169.8976, 192.0301, 136.5279]) 	 Cost: 38.687496
Epoch    7/20 	 hypothesis: tensor([151.1574, 181.6346, 172.4254, 194.8856, 138.5585]) 	 Cost: 16.499043
Epoch    8/20 	 hypothesis: tensor([152.4131, 183.1435, 173.8590, 196.5043, 139.7097]) 	 Cost: 9.365656
Epoch    9/20 	 hypothesis: tensor([153.1250, 183.9988, 174.6723, 197.4217, 140.3

# nn.Module로 구현하는 선형 회귀

In [42]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [43]:
torch.manual_seed(1)

In [44]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [45]:
# 모델을 선언 및 초기화. 단순 선형 회귀이므로 input_dim = 1, output_dim = 1
# nn.Linear(input_dim, output_dim)
model = nn.Linear(1,1)


In [46]:
print(list(model.parameters()))
# 첫번째 값이 W 값
# 두번째 값이 b 값
# 두값 모두 학습의 대상이므로 requires_grad=True가 되어져 있는 것 확인

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [47]:
# optimizer 설정. 경사 하강법 SGD를 사용하고 learning rate를 의미하는 lr은 0.01
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)

In [48]:
# 전체 훈련 데이터에 대해 경사 하강법을 2000회 반복

nb_epochs = 2000
for epoch in range(nb_epochs + 1) :
    
    # H(x) 계산
    prediction = model(x_train)
    
    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수
    
    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward() # backward연산
    # W와 b를 업데이트
    optimizer.step()
    
    # 100번마다 로그 출력
    if epoch % 100 == 0 :
        print('Epoch {:4d} / {} \t Cost : {:.6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0 / 2000 	 Cost : 13.103541
Epoch  100 / 2000 	 Cost : 0.002791
Epoch  200 / 2000 	 Cost : 0.001724
Epoch  300 / 2000 	 Cost : 0.001066
Epoch  400 / 2000 	 Cost : 0.000658
Epoch  500 / 2000 	 Cost : 0.000407
Epoch  600 / 2000 	 Cost : 0.000251
Epoch  700 / 2000 	 Cost : 0.000155
Epoch  800 / 2000 	 Cost : 0.000096
Epoch  900 / 2000 	 Cost : 0.000059
Epoch 1000 / 2000 	 Cost : 0.000037
Epoch 1100 / 2000 	 Cost : 0.000023
Epoch 1200 / 2000 	 Cost : 0.000014
Epoch 1300 / 2000 	 Cost : 0.000009
Epoch 1400 / 2000 	 Cost : 0.000005
Epoch 1500 / 2000 	 Cost : 0.000003
Epoch 1600 / 2000 	 Cost : 0.000002
Epoch 1700 / 2000 	 Cost : 0.000001
Epoch 1800 / 2000 	 Cost : 0.000001
Epoch 1900 / 2000 	 Cost : 0.000000
Epoch 2000 / 2000 	 Cost : 0.000000


In [49]:
# 임의의 입력 5를 선언
new_var = torch.FloatTensor([[4.0]])

# 입력한 값 4에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) # forward연산
# y = 2x 이므로 입력이 4라면 y가 8에 가까운 값이 나와야 제대로 학습이 된 것
print('훈련 후 입력이 4일 때의 예측값 :', pred_y)

훈련 후 입력이 4일 때의 예측값 : tensor([[7.9989]], grad_fn=<AddmmBackward0>)


In [50]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


In [2]:
import torch 
import torch.nn as nn
import torch.nn.functional as F

In [52]:
torch.manual_seed(1)

In [53]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [55]:
# 모델을 선언 및 초기화. 다중 선형 회귀이므로 input_dim = 3, output_dim = 1
model =  nn.Linear(3, 1)

In [56]:
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]


In [57]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [58]:
nb_epochs = 2000
for epoch in range(nb_epochs+1) :
    
    # H(x) 계산
    prediction = model(x_train)
    # model(x_train)은 model.forward(x_train)와 동일함.
    
    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수
    
    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()
    
    if epoch % 100 == 0 :
        # 100번마다 로그 출력
        print('Epoch {:4d}/{} \t Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0/2000 	 Cost: 31667.599609
Epoch  100/2000 	 Cost: 0.225993
Epoch  200/2000 	 Cost: 0.223911
Epoch  300/2000 	 Cost: 0.221941
Epoch  400/2000 	 Cost: 0.220059
Epoch  500/2000 	 Cost: 0.218271
Epoch  600/2000 	 Cost: 0.216575
Epoch  700/2000 	 Cost: 0.214950
Epoch  800/2000 	 Cost: 0.213413
Epoch  900/2000 	 Cost: 0.211952
Epoch 1000/2000 	 Cost: 0.210559
Epoch 1100/2000 	 Cost: 0.209230
Epoch 1200/2000 	 Cost: 0.207967
Epoch 1300/2000 	 Cost: 0.206762
Epoch 1400/2000 	 Cost: 0.205618
Epoch 1500/2000 	 Cost: 0.204529
Epoch 1600/2000 	 Cost: 0.203481
Epoch 1700/2000 	 Cost: 0.202486
Epoch 1800/2000 	 Cost: 0.201539
Epoch 1900/2000 	 Cost: 0.200634
Epoch 2000/2000 	 Cost: 0.199770


In [59]:
# 임의의 입력 [73, 80, 75]를 선언
new_var = torch.FloatTensor([[73, 80, 75]])
# 입력한 값[73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var)
print('훈련 후 입력이 73, 80, 75일 때의 예측값 :', pred_y)

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[151.2306]], grad_fn=<AddmmBackward0>)


In [60]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.9778, 0.4539, 0.5768]], requires_grad=True), Parameter containing:
tensor([0.2802], requires_grad=True)]


# 3-5 클래스로 파이토치 모델 구현하기

In [61]:
# 모델을 선언 및 초기화. 단순 선형이므로 input_dim=1, output_dim=1
model = nn.Linear(1, 1)

In [3]:
# 위에 모델을 클래스로 구현
class LinearRegressionModel(nn.Module) :
    def __init__(self) :
        super().__init__()
        self.linear = nn.Linear(1,1) # 단순 선형 회귀이므로 input_dim=1, output_dim = 1
        
    def forward(self, x) :
        return self.linear(x)
    
# 이 모델은 nn.Module을 상속 받는다. 그리고 __init__()에서 모델의 구조와 동장을 정의하는 생성자를 정의한다.
# super()함수를 부르면 여기서 만든 클래스는 nn.Module 클래스의 속성들을 가지고 초기화 된다.
# forward() 함수는 모델이 학습데이터를 입력받아서 forward 연산을 진행시키는 함수이다.
# 이 forward() 함수는 model 객체를 데이터와 함께 호출하면 자동으로 실행이 된다.
# forward 연산 이란 ? H(x)식에 입력 x로부터 예측된 y를 얻는 것

In [4]:
model = LinearRegressionModel()

In [5]:
# 모델을 선언 및 초기화 다중 선형 회귀이므로 input_dim = 3, output_dim = 1
model = nn.Linear(3,1)

In [6]:
# 위에 모델을 클래스로 구현
class MultivariateLinearRegressionModel(nn.Module) :
    def __init__(self) :
        super().__init__()
        self.linear = nn.Linear(3,1) # 다중 선형 회귀이므로 input_dim=3, output_dim = 1
    
    def forward(self, x) :
        return self.linear(x)

In [7]:
model = MultivariateLinearRegressionModel()

In [8]:
# 단순 선형회귀 클래스로 구현하기

import torch
import torch.nn as nn
import torch.nn.functional as F

In [9]:
torch.manual_seed(1)

In [10]:
# 데이터
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

In [11]:
class LinearRegressionModel(nn.Module) :
    def __init__(self) :
        super().__init__()
        self.linear = nn.Linear(1,1)
        
    def forward(self, x) :
        return self.linear(x)

In [12]:
model = LinearRegressionModel()

In [13]:
# optimizer 설정, 경사 하강법 SGD를 사용하고 learning rate를 의미하는 lr은 0.01
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)

In [14]:
# 전체 훈련 데이터에 대해 경사 하강법을 2000회 반복

nb_epochs = 2000
for epoch in range(nb_epochs+1) :
    
    # H(x) 계산
    prediction = model(x_train)
    
    # cost 계산
    cost = F.mse_loss(prediction, y_train) # 파이토치에서 제공하는 평균 제곱 오차 함수
    
    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient를 계산
    cost.backward() # backward 연산
    # W와 b를 업데이트
    optimizer.step()
    
    if epoch % 100 == 0 :
        # 100번마다 로그 출력
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [15]:
# 다중 선형 회귀 클래스로 구현하기
import torch
import torch.nn as nn
import torch.nn.functional as F

In [16]:
torch.manual_seed(1)

In [17]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [18]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1) # 다중 선형 회귀이므로 input_dim=3, output_dim=1.

    def forward(self, x):
        return self.linear(x)

In [19]:
model = MultivariateLinearRegressionModel()

In [20]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) 

In [21]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)
    # model(x_train)은 model.forward(x_train)와 동일함.

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 31667.599609
Epoch  100/2000 Cost: 0.225993
Epoch  200/2000 Cost: 0.223911
Epoch  300/2000 Cost: 0.221941
Epoch  400/2000 Cost: 0.220059
Epoch  500/2000 Cost: 0.218271
Epoch  600/2000 Cost: 0.216575
Epoch  700/2000 Cost: 0.214950
Epoch  800/2000 Cost: 0.213413
Epoch  900/2000 Cost: 0.211952
Epoch 1000/2000 Cost: 0.210559
Epoch 1100/2000 Cost: 0.209230
Epoch 1200/2000 Cost: 0.207967
Epoch 1300/2000 Cost: 0.206762
Epoch 1400/2000 Cost: 0.205618
Epoch 1500/2000 Cost: 0.204529
Epoch 1600/2000 Cost: 0.203481
Epoch 1700/2000 Cost: 0.202486
Epoch 1800/2000 Cost: 0.201539
Epoch 1900/2000 Cost: 0.200634
Epoch 2000/2000 Cost: 0.199770


# 3-6 미니 배치와 데이터 로드

In [22]:
# 데이터 로드하기
# 데이터셋과 데이터로더를 사용하면 미니배치 학습, 데이터 셔플, 병렬처리까지 간단히 수행 할 수 있다.
# 기본적인 사용방법은 Dataset을 정의하고, 이를 DataLoader에 전달하는 것 이다.

In [23]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [24]:
from torch.utils.data import TensorDataset # 텐서 데이터셋
from torch.utils.data import DataLoader # 데이터로더

In [25]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  90], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [26]:
dataset = TensorDataset(x_train, y_train)

In [27]:
# 데이터로더는 기본적으로 2개의 인자를 입력받는다. 하나는 데이터셋, 또 하나는 미니 배치의 크기이다.
# 그리고 추가적으로 많이 사용되는 인자로 shuffle이 있다.
# shuffle = True를 선택하면 Epoch 마다 데이터셋을 섞어서 데이터가 학습되는 순서를 바꾼다.

In [28]:
dataloader = DataLoader(dataset, batch_size=2, shuffle = True)

In [29]:
model = nn.Linear(3,1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [32]:
nb_eopchs = 20
for epoch in range(nb_epochs +1) :
    for batch_idx, samples in enumerate(dataloader) :
        # print(batch_idx)
        # print(samples)
        x_train, y_train = samples
        
        # H(x) 계산
        prediction = model(x_train)
        
        # cost 계산
        cost = F.mse_loss(prediction, y_train)
        
        # cost로 H(x) 계산
        optimizer.zero_grad()
        cost.backward()
        optimizer.step()
        
        print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, batch_idx+1, len(dataloader),
        cost.item()
        ))

Epoch    0/2000 Batch 1/3 Cost: 1.065262
Epoch    0/2000 Batch 2/3 Cost: 0.667054
Epoch    0/2000 Batch 3/3 Cost: 0.992020
Epoch    1/2000 Batch 1/3 Cost: 1.287326
Epoch    1/2000 Batch 2/3 Cost: 0.607313
Epoch    1/2000 Batch 3/3 Cost: 0.518050
Epoch    2/2000 Batch 1/3 Cost: 0.694060
Epoch    2/2000 Batch 2/3 Cost: 1.139801
Epoch    2/2000 Batch 3/3 Cost: 0.004166
Epoch    3/2000 Batch 1/3 Cost: 0.192934
Epoch    3/2000 Batch 2/3 Cost: 1.425121
Epoch    3/2000 Batch 3/3 Cost: 1.540302
Epoch    4/2000 Batch 1/3 Cost: 0.815379
Epoch    4/2000 Batch 2/3 Cost: 1.032482
Epoch    4/2000 Batch 3/3 Cost: 0.002422
Epoch    5/2000 Batch 1/3 Cost: 0.200694
Epoch    5/2000 Batch 2/3 Cost: 1.152314
Epoch    5/2000 Batch 3/3 Cost: 0.865823
Epoch    6/2000 Batch 1/3 Cost: 1.324458
Epoch    6/2000 Batch 2/3 Cost: 0.986112
Epoch    6/2000 Batch 3/3 Cost: 0.559688
Epoch    7/2000 Batch 1/3 Cost: 0.446626
Epoch    7/2000 Batch 2/3 Cost: 2.280510
Epoch    7/2000 Batch 3/3 Cost: 0.004846
Epoch    8/2000 

In [33]:
# 임의의 입력 [73, 80, 75]를 선언
new_var = torch.FloatTensor([[73, 80, 75]])
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴 받아서 pred_y에 저장
pred_y = model(new_var)
print('훈련 후 입력이 73, 80, 75일 때의 예측값 :', pred_y)

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[151.1515]], grad_fn=<AddmmBackward0>)


# 3-7 커스템 데이터셋

In [34]:
# class CustomDataset(torch.utils.data.Dataset): 
#   def __init__(self):
#   데이터셋의 전처리를 해주는 부분

#   def __len__(self):
#   데이터셋의 길이. 즉, 총 샘플의 수를 적어주는 부분

#   def __getitem__(self, idx): 
#   데이터셋에서 특정 1개의 샘플을 가져오는 함수

In [35]:
# 커스텀 데이터셋으로 선형 회귀 구현하기
import torch
import torch.nn.functional as F
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

In [36]:
# Dataset 상속 

class CustomDataset(Dataset) :
    def __init__(self) :
        self.x_data = [[73, 80, 75],
                   [93, 88, 93],
                   [89, 91, 90],
                   [96, 98, 100],
                   [73, 66, 70]]
        self.y_data = [[152], [185], [180], [196], [142]]
    
    # 총 데이터의 개수를 리턴
    def __len__(self) :
        return len(self.x_data)
    
    # 인덱스를 입력받아 그에 맵핑되는 입출력 데이터를 파이토치의 Tensor 형태로 리턴
    def __getitem__(self, idx)  :
        x = torch.FloatTensor(self.x_data[idx])
        y = torch.FloatTensor(self.y_data[idx])
        
        return x, y

In [37]:
dataset = CustomDataset()
dataloader = DataLoader(dataset, batch_size = 2, shuffle = True)


In [38]:
model = torch.nn.Linear(3,1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [40]:
nb_eopchs = 20
for epoch in range(nb_epochs + 1) :
    for batch_idx, samples in enumerate(dataloader) :
        #print(batch_idx)
        #print(samples)
        x_train, y_train = samples
        
        # H(x) 계산
        prediction = model(x_train)
        
        # cost 계산
        cost = F.mse_loss(prediction, y_train)
        
        # cost로 H(x) 계산
        optimizer.zero_grad()
        cost.backward()
        optimizer.step()
        
        print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, batch_idx+1, len(dataloader),
        cost.item()
        ))

Epoch    0/2000 Batch 1/3 Cost: 15074.156250
Epoch    0/2000 Batch 2/3 Cost: 7267.330078
Epoch    0/2000 Batch 3/3 Cost: 939.445496
Epoch    1/2000 Batch 1/3 Cost: 499.373108
Epoch    1/2000 Batch 2/3 Cost: 292.015869
Epoch    1/2000 Batch 3/3 Cost: 6.355498
Epoch    2/2000 Batch 1/3 Cost: 21.698128
Epoch    2/2000 Batch 2/3 Cost: 11.947321
Epoch    2/2000 Batch 3/3 Cost: 23.601664
Epoch    3/2000 Batch 1/3 Cost: 4.831841
Epoch    3/2000 Batch 2/3 Cost: 9.505085
Epoch    3/2000 Batch 3/3 Cost: 6.725639
Epoch    4/2000 Batch 1/3 Cost: 3.970273
Epoch    4/2000 Batch 2/3 Cost: 6.863029
Epoch    4/2000 Batch 3/3 Cost: 8.918885
Epoch    5/2000 Batch 1/3 Cost: 2.466089
Epoch    5/2000 Batch 2/3 Cost: 16.204035
Epoch    5/2000 Batch 3/3 Cost: 0.108197
Epoch    6/2000 Batch 1/3 Cost: 3.475802
Epoch    6/2000 Batch 2/3 Cost: 7.151284
Epoch    6/2000 Batch 3/3 Cost: 12.201662
Epoch    7/2000 Batch 1/3 Cost: 7.310730
Epoch    7/2000 Batch 2/3 Cost: 5.296537
Epoch    7/2000 Batch 3/3 Cost: 5.89285

In [41]:
# 임의의 입력 [73, 80, 75]를 선언
new_var =  torch.FloatTensor([[73, 80, 75]]) 
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) 

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[152.2742]], grad_fn=<AddmmBackward0>)
