In [1]:
import torch 
import numpy as np

In [2]:
# 텐서 초기화하기
# 데이터로부터 직접 생성하기

data = [[1,2], [3,4]]
x_data = torch.tensor(data)

print(x_data)

tensor([[1, 2],
        [3, 4]])


In [4]:
# numpy 배열로부터 생성하기

arr = np.array(data)
x_np = torch.from_numpy(arr)

print(x_np)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [5]:
# 다른 텐서로부터 생성하기

x_ones = torch.ones_like(x_data) # x_data의 속성을 유지
print(f'Ones Tensor : \n {x_ones} \n ')

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 속성을 덮어쓴다.
print(f'Random Tensor : \n {x_rand} \n')

Ones Tensor : 
 tensor([[1, 1],
        [1, 1]]) 
 
Random Tensor : 
 tensor([[0.9434, 0.3300],
        [0.2161, 0.8874]]) 



In [7]:
# 무작위(random) 또는 상수(constant)값을 사용하기 

shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f'Random Tensor : \n {rand_tensor} \n')
print(f'Ones Tensor : \n {ones_tensor} \n')
print(f'Zeros Tensor : \n {zeros_tensor} \n')

Random Tensor : 
 tensor([[0.7794, 0.8004, 0.0786],
        [0.1132, 0.4497, 0.1062]]) 

Ones Tensor : 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor : 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [8]:
# 텐서의 속성

tensor = torch.rand(3, 4)

print(f'Shape of tensor : {tensor.shape}')
print(f'Datatype of tensor : {tensor.dtype}')
print(f'Device tensor is stored on : {tensor.device}')

Shape of tensor : torch.Size([3, 4])
Datatype of tensor : torch.float32
Device tensor is stored on : cpu


In [9]:
# 텐서 연산

# GPU가 존재하면 텐서를 이동한다.
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [10]:
# numpy식 표준 인덱싱과 슬라이싱 :
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
