In [1]:
import torch
import torch.nn.functional as F

In [2]:
tensor = torch.FloatTensor([0.5, 0.7, 0.1])
h_tensor = F.softmax(tensor, dim = 0)
h_tensor

tensor([0.3458, 0.4224, 0.2318])

In [7]:
y = torch.randint(5, (10, 5))
y_label = y.argmax(dim=1)
y_label

tensor([0, 1, 3, 1, 0, 0, 0, 0, 1, 4])

In [8]:
torch.nn.functional.one_hot(y_label)
F.one_hot(y_label)

tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 1, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1]])

## Cartesian_prod

In [9]:
import itertools

a = [1, 2]
b = [4, 5]

list(itertools.product(a,b))

[(1, 4), (1, 5), (2, 4), (2, 5)]

In [10]:
import torch

tensor_a = torch.tensor(a)
tensor_b = torch.tensor(b)
torch.cartesian_prod(tensor_a, tensor_b)

tensor([[1, 4],
        [1, 5],
        [2, 4],
        [2, 5]])

## Torch autograd
$$
y = w^2 \\ 
z = 10*y + 50 \\
z = 10*w^2 + 50 
$$

In [12]:
w = torch.tensor(2.0, requires_grad=True)
y = w ** 2
z = 10 * y + 50

z.backward()
w.grad

tensor(40.)

$$ Q = 3a^3 - b^2  $$

In [15]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

q = 3*a**3 - b**2

external_grad = torch.tensor([1., 1.])
q.backward(gradient = external_grad)
b.grad

tensor([-12.,  -8.])

In [16]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=False)

q = 3*a**3 - b**2

external_grad = torch.tensor([1., 1.])
q.backward(gradient = external_grad)
b.grad # b가 False라서 미분안됨

In [17]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

q = 3*a**3 - b**2

external_grad = torch.tensor([2., 2.]) # 2배했더니 결과도 두배
q.backward(gradient = external_grad)
b.grad

tensor([-24., -16.])

$$ \frac{\partial Q}{\partial a} = 9a^2 $$  

$$ \frac{\partial Q}{\partial b} = -2b $$