In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv('./tmdb_5000_movies.csv')
movies.head()

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

In [3]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [4]:
# 필요한 변수(column)만 추출

df = movies[['id', 'title', 'genres','vote_average','vote_count', 'popularity', 'keywords', 'overview']]
df

id                                     title  \
0      19995                                    Avatar   
1        285  Pirates of the Caribbean: At World's End   
2     206647                                   Spectre   
3      49026                     The Dark Knight Rises   
4      49529                               John Carter   
...      ...                                       ...   
4798    9367                               El Mariachi   
4799   72766                                 Newlyweds   
4800  231617                 Signed, Sealed, Delivered   
4801  126186                          Shanghai Calling   
4802   25975                         My Date with Drew   

                                                 genres  vote_average  \
0     [{"id": 28, "name": "Action"}, {"id": 12, "nam...           7.2   
1     [{"id": 12, "name": "Adventure"}, {"id": 14, "...           6.9   
2     [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.3   
3     [{"id": 28, "name": "Action"}, {"id": 80, "nam...           7.6   
4     [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.1   
...                                                 ...           ...   
4798  [{"id": 28, "name": "Action"}, {"id": 80, "nam...           6.6   
4799  [{"id": 35, "name": "Comedy"}, {"id": 10749, "...           5.9   
4800  [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...           7.0   
4801                                                 []           5.7   
4802                [{"id": 99, "name": "Documentary"}]           6.3   

      vote_count  popularity  \
0          11800  150.437577   
1           4500  139.082615   
2           4466  107.376788   
3           9106  112.312950   
4           2124   43.926995   
...          ...         ...   
4798         238   14.269792   
4799           5    0.642552   
4800           6    1.444476   
4801           7    0.857008   
4802          16    1.929883   

                                               keywords  \
0     [{"id": 1463, "name": "culture clash"}, {"id":...   
1     [{"id": 270, "name": "ocean"}, {"id": 726, "na...   
2     [{"id": 470, "name": "spy"}, {"id": 818, "name...   
3     [{"id": 849, "name": "dc comics"}, {"id": 853,...   
4     [{"id": 818, "name": "based on novel"}, {"id":...   
...                                                 ...   
4798  [{"id": 5616, "name": "united states\u2013mexi...   
4799                                                 []   
4800  [{"id": 248, "name": "date"}, {"id": 699, "nam...   
4801                                                 []   
4802  [{"id": 1523, "name": "obsession"}, {"id": 224...   

                                               overview  
0     In the 22nd century, a paraplegic Marine is di...  
1     Captain Barbossa, long believed to be dead, ha...  
2     A cryptic message from Bond’s past sends him o...  
3     Following the death of District Attorney Harve...  
4     John Carter is a war-weary, former military ca...  
...                                                 ...  
4798  El Mariachi just wants to play his guitar and ...  
4799  A newlywed couple's honeymoon is upended by th...  
4800  "Signed, Sealed, Delivered" introduces a dedic...  
4801  When ambitious New York attorney Sam is sent t...  
4802  Ever since the second grade when he first saw ...  

[4803 rows x 8 columns]

In [5]:
df['genres'][:10]

0    [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1    [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2    [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3    [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4    [{"id": 28, "name": "Action"}, {"id": 12, "nam...
5    [{"id": 14, "name": "Fantasy"}, {"id": 28, "na...
6    [{"id": 16, "name": "Animation"}, {"id": 10751...
7    [{"id": 28, "name": "Action"}, {"id": 12, "nam...
8    [{"id": 12, "name": "Adventure"}, {"id": 14, "...
9    [{"id": 28, "name": "Action"}, {"id": 12, "nam...
Name: genres, dtype: object

In [6]:
type(df['genres'][0])
# str 타입인 것을 확인

str

In [7]:
# genres, keywords 컬럼 전처리(정제) 필요 str >> list
from ast import literal_eval# 문자열 파싱 라이브러리
df['genres'] = df['genres'].apply(literal_eval)
df['keywords'] = df['keywords'].apply(literal_eval)

C:\Users\SBAUser\AppData\Local\Temp\ipykernel_15004\3851732947.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['genres'] = df['genres'].apply(literal_eval)
C:\Users\SBAUser\AppData\Local\Temp\ipykernel_15004\3851732947.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['keywords'] = df['keywords'].apply(literal_eval)


In [8]:
df['genres'][0]


[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [9]:
type(df['genres'][0])

list

In [10]:
df['genres'].apply(lambda x : [y['name'] for y in x])

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...                      
4798                        [Action, Crime, Thriller]
4799                                [Comedy, Romance]
4800               [Comedy, Drama, Romance, TV Movie]
4801                                               []
4802                                    [Documentary]
Name: genres, Length: 4803, dtype: object

In [11]:
df['genres'] = df['genres'].apply(lambda x : [y['name'] for y in x])
df['keywords'] = df['keywords'].apply(lambda x : [y['name'] for y in x])

C:\Users\SBAUser\AppData\Local\Temp\ipykernel_15004\1904895770.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['genres'] = df['genres'].apply(lambda x : [y['name'] for y in x])
C:\Users\SBAUser\AppData\Local\Temp\ipykernel_15004\1904895770.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['keywords'] = df['keywords'].apply(lambda x : [y['name'] for y in x])


In [12]:
df[['genres', 'keywords']]

genres  \
0     [Action, Adventure, Fantasy, Science Fiction]   
1                      [Adventure, Fantasy, Action]   
2                        [Action, Adventure, Crime]   
3                  [Action, Crime, Drama, Thriller]   
4              [Action, Adventure, Science Fiction]   
...                                             ...   
4798                      [Action, Crime, Thriller]   
4799                              [Comedy, Romance]   
4800             [Comedy, Drama, Romance, TV Movie]   
4801                                             []   
4802                                  [Documentary]   

                                               keywords  
0     [culture clash, future, space war, space colon...  
1     [ocean, drug abuse, exotic island, east india ...  
2     [spy, based on novel, secret agent, sequel, mi...  
3     [dc comics, crime fighter, terrorist, secret i...  
4     [based on novel, mars, medallion, space travel...  
...                                                 ...  
4798  [united states–mexico barrier, legs, arms, pap...  
4799                                                 []  
4800  [date, love at first sight, narration, investi...  
4801                                                 []  
4802          [obsession, camcorder, crush, dream girl]  

[4803 rows x 2 columns]

In [13]:
# 장르 컨텐츠 유사도 측정

from sklearn.feature_extraction.text import CountVectorizer

In [14]:
# CounterVectorizer
# 1. 문서 >> 토큰 리스트로 변환
# 2. 각 문서에서 토큰 출현 빈도를 센다
# 3. 각 문서를 BOW(bag of words_단어 주머니) 인코딩 벡터로 변환

corpus = [
    'This is the first document.',
    'This is the second document.',
    'And the third one',
    'Is this the first document?',
    'The last document?'
]

vect = CountVectorizer()
vect.fit(corpus)
vect.vocabulary_

{'this': 9,
 'is': 3,
 'the': 7,
 'first': 2,
 'document': 1,
 'second': 6,
 'and': 0,
 'third': 8,
 'one': 5,
 'last': 4}

In [15]:
df['genres'][:5]

0    [Action, Adventure, Fantasy, Science Fiction]
1                     [Adventure, Fantasy, Action]
2                       [Action, Adventure, Crime]
3                 [Action, Crime, Drama, Thriller]
4             [Action, Adventure, Science Fiction]
Name: genres, dtype: object

In [16]:
# CountVectorizer 적용하기 위해 공백문자로 word 단위로 구분되는 문자열로 변환

df['genre_literal'] = df['genres'].apply(lambda x : (' ').join(x))
df['genre_literal'][:1]

C:\Users\SBAUser\AppData\Local\Temp\ipykernel_15004\524088563.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['genre_literal'] = df['genres'].apply(lambda x : (' ').join(x))


0    Action Adventure Fantasy Science Fiction
Name: genre_literal, dtype: object

In [17]:
# CountVectorizer로 학습

count_vec = CountVectorizer(min_df = 0, ngram_range = (1,2))
# min_df : 단어장에 들어갈 최소 빈도(초기화), ngram_range = (1, 2) : 1 <= n <= 2 (onegram or bigram)

In [18]:
count_vec.fit_transform(df['genre_literal'])
# 4803*276 (4803 : 영화 갯수) >> sparse matrix(행렬)

<4803x276 sparse matrix of type '<class 'numpy.int64'>'
	with 20631 stored elements in Compressed Sparse Row format>

In [19]:
genre_mat = count_vec.fit_transform(df['genre_literal'])
print(genre_mat.shape)

(4803, 276)


In [20]:
print(genre_mat) # onegram, bigram (0번째 onegram5개 bigram4개 > 총 9개)

  (0, 0)	1
  (0, 16)	1
  (0, 124)	1
  (0, 232)	1
  (0, 138)	1
  (0, 1)	1
  (0, 24)	1
  (0, 135)	1
  (0, 233)	1
  (1, 0)	1
  (1, 16)	1
  (1, 124)	1
  (1, 24)	1
  (1, 125)	1
  (2, 0)	1
  (2, 16)	1
  (2, 1)	1
  (2, 64)	1
  (2, 20)	1
  (3, 0)	1
  (3, 64)	1
  (3, 90)	1
  (3, 234)	1
  (3, 4)	1
  (3, 68)	1
  :	:
  (4796, 90)	1
  (4796, 234)	1
  (4796, 106)	1
  (4796, 144)	1
  (4797, 234)	1
  (4797, 153)	1
  (4797, 157)	1
  (4798, 0)	1
  (4798, 64)	1
  (4798, 234)	1
  (4798, 4)	1
  (4798, 78)	1
  (4799, 44)	1
  (4799, 214)	1
  (4799, 58)	1
  (4800, 90)	1
  (4800, 44)	1
  (4800, 214)	1
  (4800, 104)	1
  (4800, 50)	1
  (4800, 250)	1
  (4800, 182)	1
  (4800, 251)	1
  (4800, 229)	1
  (4802, 80)	1


In [74]:
# 코사인 유사도 이용, 영화별 유사도 계산

from sklearn.metrics.pairwise import cosine_similarity

genre_sim = cosine_similarity(genre_mat, genre_mat)
genre_sim

array([[1.        , 0.59628479, 0.4472136 , ..., 0.        , 0.        ,
        0.        ],
       [0.59628479, 1.        , 0.4       , ..., 0.        , 0.        ,
        0.        ],
       [0.4472136 , 0.4       , 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [77]:
genre_sim.argsort() # 인덱스 어레이 반환

array([[2401, 3037, 3038, ...,  813, 3494,    0],
       [2401, 3067, 3069, ...,  129,    1,  262],
       [2401, 2999, 3000, ..., 1542, 1740,    2],
       ...,
       [   0, 2230, 2229, ..., 1895, 3809, 4800],
       [   0, 3205, 3204, ..., 1596, 1594, 4802],
       [   0, 3141, 3140, ..., 4521, 4710, 4802]], dtype=int64)

In [24]:
# argsort : 자료를 정렬하는 것이 아님, 순서만 알고 싶을 때 사용
# 유사도 높은 영화를 앞에서부터 순서대로 보여줌
# 0번째 영화의 경우 유사도 순서 : 0번, 3494번, 813번 ... 순서

genre_sim.argsort()[:, :: -1]

array([[   0, 3494,  813, ..., 3038, 3037, 2401],
       [ 262,    1,  129, ..., 3069, 3067, 2401],
       [   2, 1740, 1542, ..., 3000, 2999, 2401],
       ...,
       [4800, 3809, 1895, ..., 2229, 2230,    0],
       [4802, 1594, 1596, ..., 3204, 3205,    0],
       [4802, 4710, 4521, ..., 3140, 3141,    0]], dtype=int64)

In [32]:
genre_sim_sorted_ind = genre_sim.argsort()[:,::-1]

genre_sim_sorted_ind[:5]

array([[   0, 3494,  813, ..., 3038, 3037, 2401],
       [ 262,    1,  129, ..., 3069, 3067, 2401],
       [   2, 1740, 1542, ..., 3000, 2999, 2401],
       [2195, 1850, 3316, ...,  887, 2544, 4802],
       [ 102, 2995,   56, ..., 3046, 3045, 2401]], dtype=int64)

In [27]:
# 추천 ver1 장르 코사인 유사도에 의해 영화를 추천하는 함수

# 함수 분석

# 인자로 입력된 df 데이터프레임에서 'title' 컬럼이 입력된 title_name 값인 데이터프레임 추출

condition = df['title'] == 'The Godfather'
df[condition]

id          title          genres  vote_average  vote_count  \
3337  238  The Godfather  [Drama, Crime]           8.4        5893   

      popularity                                           keywords  \
3337  143.659698  [italy, love at first sight, loss of father, p...   

                                               overview genre_literal  
3337  Spanning the years 1945 to 1955, a chronicle o...   Drama Crime

In [28]:
title_movie = df[condition]
# title_name 을 가진 데이터프레임에서 index 객체를 넘파이 이용 ndarray 반환
# sorted_ind 인자로 입력된 genre_sim_sorted_ind 객체에서 유사도 순으로 top_n개의 index 추출

In [31]:
title_index = title_movie.index.values
title_index

array([3337], dtype=int64)

In [34]:
genre_sim_sorted_ind[title_index, : 10]

array([[2731, 1243, 3636, 1946, 2640, 4065, 1847, 4217,  883, 3866]],
      dtype=int64)

In [37]:
similar_indexes = genre_sim_sorted_ind[title_index, : 10]
similar_indexes

array([[2731, 1243, 3636, 1946, 2640, 4065, 1847, 4217,  883, 3866]],
      dtype=int64)

In [38]:
# 추출된 top_n index 출력, top_n index 2차원 데이터
# 데이터프레임에서 index 사용하기 위해 2차원 array >> 1차원 array로 변경
similar_indexes.reshape(-1)

array([2731, 1243, 3636, 1946, 2640, 4065, 1847, 4217,  883, 3866],
      dtype=int64)

In [39]:
similar_index = similar_indexes.reshape(-1)
similar_index

array([2731, 1243, 3636, 1946, 2640, 4065, 1847, 4217,  883, 3866],
      dtype=int64)

In [40]:
df.iloc[similar_index]

id                                           title          genres  \
2731     240                          The Godfather: Part II  [Drama, Crime]   
1243     203                                    Mean Streets  [Drama, Crime]   
3636   36351                                   Light Sleeper  [Drama, Crime]   
1946   11699  The Bad Lieutenant: Port of Call - New Orleans  [Drama, Crime]   
2640     400         Things to Do in Denver When You're Dead  [Drama, Crime]   
4065  364083                                      Mi America  [Drama, Crime]   
1847     769                                      GoodFellas  [Drama, Crime]   
4217    9344                                            Kids  [Drama, Crime]   
883      640                             Catch Me If You Can  [Drama, Crime]   
3866     598                                     City of God  [Drama, Crime]   

      vote_average  vote_count  popularity  \
2731           8.3        3338  105.792936   
1243           7.2         345   17.002096   
3636           5.7          15    6.063868   
1946           6.0         326   17.339852   
2640           6.7          85    6.932221   
4065           0.0           0    0.039007   
1847           8.2        3128   63.654244   
4217           6.8         279   13.291991   
883            7.7        3795   73.944049   
3866           8.1        1814   44.356711   

                                               keywords  \
2731  [italo-american, cuba, vororte, melancholy, pr...   
1243  [epilepsy, protection money, secret love, mone...   
3636  [suicide, drug dealer, redemption, addict, exi...   
1946  [police brutality, organized crime, policeman,...   
2640  [father son relationship, bounty hunter, boat,...   
4065                       [new york state, hate crime]   
1847  [prison, based on novel, florida, 1970s, mass ...   
4217                              [puberty, first time]   
883   [con man, biography, fbi agent, overhead camer...   
3866  [male nudity, street gang, brazilian, photogra...   

                                               overview genre_literal  
2731  In the continuing saga of the Corleone crime f...   Drama Crime  
1243  A small-time hood must choose from among love,...   Drama Crime  
3636  A drug dealer with upscale clientele is having...   Drama Crime  
1946  Terrence McDonagh, a New Orleans Police sergea...   Drama Crime  
2640  A mafia film in Tarantino style with a star-st...   Drama Crime  
4065  A hate-crime has been committed in a the small...   Drama Crime  
1847  The true story of Henry Hill, a half-Irish, ha...   Drama Crime  
4217  A controversial portrayal of teens in New York...   Drama Crime  
883   A true story about Frank Abagnale Jr. who, bef...   Drama Crime  
3866  Cidade de Deus is a shantytown that started du...   Drama Crime

In [41]:
# 실제 함수

def find_sim_movie_ver1(df, sorted_ind, title_name, top_n = 10) :
    # 인자로 입력된 df 데이터프레임에서 'title' 컬럼이 입력되니 title_name 값인 데이터 프레임 추출
    
    title_movie = df[df['title'] == title_name]
    
    # title_name을 가진 데이터프레임의 index객체를 ndarray로 반환하고
    # sorted_ind 인자로 입력된 genre_sim_sorted_ind 객체에서 유사도 순으로 top_n개의 index 추출
    
    title_index = title_movie.index.values
    similar_indexes = sorted_ind[title_index, : (top_n)]
    
    # 추출된 top_n index를 출력(2차원)
    # 데이터프레임에서 index로 사용하기 위해서는 1차원 array로 변경
    
    print(similar_indexes)
    
    # 2차원 >> 1차원
    similar_index = similar_indexes.reshape(-1)
    
    return df.iloc[similar_index]

In [45]:
# 영화 God Father와 장르가 유사한 영화 10개 추천

similar_movies = find_sim_movie_ver1(df, genre_sim_sorted_ind, 'The Godfather', 10)
similar_movies

[[2731 1243 3636 1946 2640 4065 1847 4217  883 3866]]


id                                           title          genres  \
2731     240                          The Godfather: Part II  [Drama, Crime]   
1243     203                                    Mean Streets  [Drama, Crime]   
3636   36351                                   Light Sleeper  [Drama, Crime]   
1946   11699  The Bad Lieutenant: Port of Call - New Orleans  [Drama, Crime]   
2640     400         Things to Do in Denver When You're Dead  [Drama, Crime]   
4065  364083                                      Mi America  [Drama, Crime]   
1847     769                                      GoodFellas  [Drama, Crime]   
4217    9344                                            Kids  [Drama, Crime]   
883      640                             Catch Me If You Can  [Drama, Crime]   
3866     598                                     City of God  [Drama, Crime]   

      vote_average  vote_count  popularity  \
2731           8.3        3338  105.792936   
1243           7.2         345   17.002096   
3636           5.7          15    6.063868   
1946           6.0         326   17.339852   
2640           6.7          85    6.932221   
4065           0.0           0    0.039007   
1847           8.2        3128   63.654244   
4217           6.8         279   13.291991   
883            7.7        3795   73.944049   
3866           8.1        1814   44.356711   

                                               keywords  \
2731  [italo-american, cuba, vororte, melancholy, pr...   
1243  [epilepsy, protection money, secret love, mone...   
3636  [suicide, drug dealer, redemption, addict, exi...   
1946  [police brutality, organized crime, policeman,...   
2640  [father son relationship, bounty hunter, boat,...   
4065                       [new york state, hate crime]   
1847  [prison, based on novel, florida, 1970s, mass ...   
4217                              [puberty, first time]   
883   [con man, biography, fbi agent, overhead camer...   
3866  [male nudity, street gang, brazilian, photogra...   

                                               overview genre_literal  
2731  In the continuing saga of the Corleone crime f...   Drama Crime  
1243  A small-time hood must choose from among love,...   Drama Crime  
3636  A drug dealer with upscale clientele is having...   Drama Crime  
1946  Terrence McDonagh, a New Orleans Police sergea...   Drama Crime  
2640  A mafia film in Tarantino style with a star-st...   Drama Crime  
4065  A hate-crime has been committed in a the small...   Drama Crime  
1847  The true story of Henry Hill, a half-Irish, ha...   Drama Crime  
4217  A controversial portrayal of teens in New York...   Drama Crime  
883   A true story about Frank Abagnale Jr. who, bef...   Drama Crime  
3866  Cidade de Deus is a shantytown that started du...   Drama Crime

In [46]:
similar_movies.columns

Index(['id', 'title', 'genres', 'vote_average', 'vote_count', 'popularity',
       'keywords', 'overview', 'genre_literal'],
      dtype='object')

In [48]:
similar_movies[['title', 'vote_average', 'genres', 'vote_count']]

# 문제 : 평점(vote_average)기반, 추천하고자 했는데, vote_count가 낮은 영화는 제외하고 싶어

title  vote_average  \
2731                          The Godfather: Part II           8.3   
1243                                    Mean Streets           7.2   
3636                                   Light Sleeper           5.7   
1946  The Bad Lieutenant: Port of Call - New Orleans           6.0   
2640         Things to Do in Denver When You're Dead           6.7   
4065                                      Mi America           0.0   
1847                                      GoodFellas           8.2   
4217                                            Kids           6.8   
883                              Catch Me If You Can           7.7   
3866                                     City of God           8.1   

              genres  vote_count  
2731  [Drama, Crime]        3338  
1243  [Drama, Crime]         345  
3636  [Drama, Crime]          15  
1946  [Drama, Crime]         326  
2640  [Drama, Crime]          85  
4065  [Drama, Crime]           0  
1847  [Drama, Crime]        3128  
4217  [Drama, Crime]         279  
883   [Drama, Crime]        3795  
3866  [Drama, Crime]        1814

In [49]:
df.columns

Index(['id', 'title', 'genres', 'vote_average', 'vote_count', 'popularity',
       'keywords', 'overview', 'genre_literal'],
      dtype='object')

In [51]:
# 평점기준으로 정렬(sort_values)해 보니, 평가횟수(vote_count)가 낮은 것들도 파함되어 있음
# 평가 횟수 반영한 평점(가중평점)이 필요함. 내림차순으로 상위 10개만 추출할 필요있음.
df[['title', 'genres', 'vote_average', 'vote_count']].sort_values('vote_average', ascending=False)[:10]


title                             genres  \
3519          Stiff Upper Lips                           [Comedy]   
4247     Me You and Five Bucks           [Romance, Comedy, Drama]   
4045     Dancer, Texas Pop. 81            [Comedy, Drama, Family]   
4662            Little Big Top                           [Comedy]   
3992                 Sardaarji                                 []   
2386            One Man's Hero  [Western, Action, Drama, History]   
2970        There Goes My Baby                    [Drama, Comedy]   
1881  The Shawshank Redemption                     [Drama, Crime]   
2796     The Prisoner of Zenda        [Adventure, Drama, Romance]   
3337             The Godfather                     [Drama, Crime]   

      vote_average  vote_count  
3519          10.0           1  
4247          10.0           2  
4045          10.0           1  
4662          10.0           1  
3992           9.5           2  
2386           9.3           2  
2970           8.5           2  
1881           8.5        8205  
2796           8.4          11  
3337           8.4        5893

In [53]:
# 가중평점(평점, 평가횟수) 반영한 영화 추천
# (v/(v+m))* R + (m/(v+m))*C
# 상위 60% 해당하는 vote_count 최소 투표 횟수인 m 으로 지정
# v : 영화별 평점을 투표한 횟수
# m : 평점을 부여하기 위한 최소 투표 횟수
# R : 개별 영화에 대한 평균 평점
# C : 전체 영화에 대한 평균 평점



C = df['vote_average'].mean()
# 전체 영화에 대한 평점 6.09

m = df['vote_count'].quantile(0.6)
# 370.199999
# >> 적어도 370번 이상의 평점을 준 영화의 평점을 사용

In [54]:
# C : 전체 영화에 대한 평균 평점 : 약 6점
# m : 평점을 부여하기 위하나 최소 투표 회수 : 370회(상위 60% 수준)
print('C : ', round(C, 2), '\nm : ' , round(m, 2))

C :  6.09 
m :  370.2


In [55]:
# 가중 평점을 계산하는 함수
def weighted_vote_average(record) :
    v = record['vote_count']
    R = record['vote_average']
    
    return ((v/(v+m))*R + (m/(m+v))*C)


In [57]:
# 기존 데이터에 가중평점 컬럼 추가

df['weighted_vote'] = df.apply(weighted_vote_average, axis = 1)
df['weighted_vote']

C:\Users\SBAUser\AppData\Local\Temp\ipykernel_15004\3561581403.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['weighted_vote'] = df.apply(weighted_vote_average, axis = 1)


0       7.166301
1       6.838594
2       6.284091
3       7.541095
4       6.098838
          ...   
4798    6.290894
4799    6.089611
4800    6.106650
4801    6.084894
4802    6.100782
Name: weighted_vote, Length: 4803, dtype: float64

In [58]:
# 가중평균 기준, 영화 순위 추출(내림차순) >> 평점이 높은 영화 먼저 출력

df.columns

Index(['id', 'title', 'genres', 'vote_average', 'vote_count', 'popularity',
       'keywords', 'overview', 'genre_literal', 'weighted_vote'],
      dtype='object')

In [62]:
df[['title', 'genres', 'weighted_vote', 'vote_average', 'vote_count']].sort_values('weighted_vote', ascending=False)[:10]

title                                   genres  \
1881  The Shawshank Redemption                           [Drama, Crime]   
3337             The Godfather                           [Drama, Crime]   
662                 Fight Club                                  [Drama]   
3232              Pulp Fiction                        [Thriller, Crime]   
65             The Dark Knight         [Drama, Action, Crime, Thriller]   
1818          Schindler's List                    [Drama, History, War]   
3865                  Whiplash                                  [Drama]   
809               Forrest Gump                 [Comedy, Drama, Romance]   
2294             Spirited Away  [Fantasy, Adventure, Animation, Family]   
2731    The Godfather: Part II                           [Drama, Crime]   

      weighted_vote  vote_average  vote_count  
1881       8.396052           8.5        8205  
3337       8.263591           8.4        5893  
662        8.216455           8.3        9413  
3232       8.207102           8.3        8428  
65         8.136930           8.2       12002  
1818       8.126069           8.3        4329  
3865       8.123248           8.3        4254  
809        8.105954           8.2        7927  
2294       8.105867           8.3        3840  
2731       8.079586           8.3        3338

In [63]:
# 추천 ver2 먼저 장르 유사성 높은 영화 선정 후 가중평점 순으로 선정

def find_sim_movie_ver2(df, sorted_ind, title_name, top_n = 10) :
    title_movie = df[df['title'] == title_name]
    title_index = title_movie.index.values
    
    # top_n의 2배(유사성 높은 영화 선정)에 해당하는 장르 유사성이 높은 index 추출
    similar_indexes = sorted_ind[title_index, : (top_n)*2]
    similar_index = similar_indexes.reshape(-1)
    
    # 기준 영화 index는 제외(기존에 본 영화 제외하고 추천하기 위함, title_index 겹치지 않는 영화 추천)
    similar_index = similar_index[similar_index != title_index]
    
    # top_n의 2배(후보군)에서 weighted_vote가 높은 순으로 top_n만큼 추출
    return df.iloc[similar_index].sort_values('weighted_vote', ascending = False)[:top_n]



In [65]:
# 영화 Godfather 에 대해 장르 유사성, 가중평점을 반영한 영화 10편 추천

similar_movies = find_sim_movie_ver2(df, genre_sim_sorted_ind, 'The Godfather', 10)
similar_movies[['title', 'genres', 'weighted_vote', 'vote_average', 'vote_count']]

title          genres  weighted_vote  \
2731       The Godfather: Part II  [Drama, Crime]       8.079586   
1847                   GoodFellas  [Drama, Crime]       7.976937   
3866                  City of God  [Drama, Crime]       7.759693   
1663  Once Upon a Time in America  [Drama, Crime]       7.657811   
883           Catch Me If You Can  [Drama, Crime]       7.557097   
281             American Gangster  [Drama, Crime]       7.141396   
4041              This Is England  [Drama, Crime]       6.739664   
1149              American Hustle  [Drama, Crime]       6.717525   
1243                 Mean Streets  [Drama, Crime]       6.626569   
2839                     Rounders  [Drama, Crime]       6.530427   

      vote_average  vote_count  
2731           8.3        3338  
1847           8.2        3128  
3866           8.1        1814  
1663           8.2        1069  
883            7.7        3795  
281            7.4        1502  
4041           7.4         363  
1149           6.8        2807  
1243           7.2         345  
2839           6.9         439

In [66]:
result = similar_movies[['title', 'genres', 'weighted_vote', 'vote_average', 'vote_count']]
result

title          genres  weighted_vote  \
2731       The Godfather: Part II  [Drama, Crime]       8.079586   
1847                   GoodFellas  [Drama, Crime]       7.976937   
3866                  City of God  [Drama, Crime]       7.759693   
1663  Once Upon a Time in America  [Drama, Crime]       7.657811   
883           Catch Me If You Can  [Drama, Crime]       7.557097   
281             American Gangster  [Drama, Crime]       7.141396   
4041              This Is England  [Drama, Crime]       6.739664   
1149              American Hustle  [Drama, Crime]       6.717525   
1243                 Mean Streets  [Drama, Crime]       6.626569   
2839                     Rounders  [Drama, Crime]       6.530427   

      vote_average  vote_count  
2731           8.3        3338  
1847           8.2        3128  
3866           8.1        1814  
1663           8.2        1069  
883            7.7        3795  
281            7.4        1502  
4041           7.4         363  
1149           6.8        2807  
1243           7.2         345  
2839           6.9         439

In [68]:
# Spidr-Man 3
result = find_sim_movie_ver2(df, genre_sim_sorted_ind, 'Spider-Man 3', 10)
result[['title', 'genres', 'weighted_vote', 'vote_average', 'vote_count']]

title  \
329      The Lord of the Rings: The Return of the King   
262  The Lord of the Rings: The Fellowship of the Ring   
330              The Lord of the Rings: The Two Towers   
19           The Hobbit: The Battle of the Five Armies   
98                   The Hobbit: An Unexpected Journey   
126                               Thor: The Dark World   
30                                        Spider-Man 2   
129                                               Thor   
20                              The Amazing Spider-Man   
38                            The Amazing Spider-Man 2   

                           genres  weighted_vote  vote_average  vote_count  
329  [Adventure, Fantasy, Action]       8.011871           8.1        8064  
262  [Adventure, Fantasy, Action]       7.922175           8.0        8705  
330  [Adventure, Fantasy, Action]       7.910111           8.0        7487  
19   [Action, Adventure, Fantasy]       7.027274           7.1        4760  
98   [Adventure, Fantasy, Action]       6.961224           7.0        8297  
126  [Action, Adventure, Fantasy]       6.748873           6.8        4755  
30   [Action, Adventure, Fantasy]       6.652034           6.7        4321  
129  [Adventure, Fantasy, Action]       6.572735           6.6        6525  
20   [Action, Adventure, Fantasy]       6.478296           6.5        6586  
38   [Action, Adventure, Fantasy]       6.466812           6.5        4179