# 넘파이 복습

In [1]:
import numpy as np
import pandas as pd

In [14]:
A = np.array([
        [3,3,2,3,1],
        [5,2,2,3,1],
        [3,3,2,3,1],
        [3,1,4,3,1],
])

In [15]:
B = np.array([
    [1,1,1,1,1],
    [2,2,2,2,2],
    [3,3,3,3,3],
    [4,4,4,4,4],
])

In [16]:
A + B

array([[4, 4, 3, 4, 2],
       [7, 4, 4, 5, 3],
       [6, 6, 5, 6, 4],
       [7, 5, 8, 7, 5]])

In [17]:
A - B

array([[ 2,  2,  1,  2,  0],
       [ 3,  0,  0,  1, -1],
       [ 0,  0, -1,  0, -2],
       [-1, -3,  0, -1, -3]])

In [18]:
A * B

array([[ 3,  3,  2,  3,  1],
       [10,  4,  4,  6,  2],
       [ 9,  9,  6,  9,  3],
       [12,  4, 16, 12,  4]])

In [19]:
A / B

array([[3.        , 3.        , 2.        , 3.        , 1.        ],
       [2.5       , 1.        , 1.        , 1.5       , 0.5       ],
       [1.        , 1.        , 0.66666667, 1.        , 0.33333333],
       [0.75      , 0.25      , 1.        , 0.75      , 0.25      ]])

In [20]:
A @ B.T

array([[12, 24, 36, 48],
       [13, 26, 39, 52],
       [12, 24, 36, 48],
       [12, 24, 36, 48]])

In [21]:
C = np.array([
        [3,3,2,3,1],
        [5,2,2,3,1],
        [3,3,np.nan,3,1],
        [3,1,4,3,1],
])

D = np.array([
    [1,np.nan,1,1,1],
    [2,2,2,2,2],
    [3,3,3,3,3],
    [np.nan,4,4,4,4],
])

In [22]:
C + D

array([[ 4., nan,  3.,  4.,  2.],
       [ 7.,  4.,  4.,  5.,  3.],
       [ 6.,  6., nan,  6.,  4.],
       [nan,  5.,  8.,  7.,  5.]])

In [23]:
5 * C

array([[15., 15., 10., 15.,  5.],
       [25., 10., 10., 15.,  5.],
       [15., 15., nan, 15.,  5.],
       [15.,  5., 20., 15.,  5.]])

In [27]:
np.sum(C)

nan

In [28]:
np.sum(A)

49

In [29]:
# nan 값 제외하고 계산하기
np.nansum(C)

47.0

In [30]:
np.mean(A)

2.45

In [31]:
np.nanmean(C)

2.473684210526316

In [33]:
print(A[0])
print(A[3])

[3 3 2 3 1]
[3 1 4 3 1]


In [34]:
print(A[:, 3])

[3 3 3 3]


# 넘파이 활용, user(사용자) 간 거리 구하기

In [35]:
import numpy as np
import pandas as pd
from math import sqrt

In [51]:
def distance(user_1, user_2) :
    '''유클리드 거리를 계산해 주는 함수'''
    sum = 0
    for i in range(len(user_1)) :
        sum += (user_1[i] - user_2[i])**2
    return sqrt(sum)

In [52]:
# 실행코드
user_1 = np.array([0,1,2,3,4,5])
user_2 = np.array([0,1,4,6,1,4])

distance(user_1, user_2)

4.795831523312719

In [54]:
distance([2,3], [4,4])

2.23606797749979

In [55]:
def distance(user_1, user_2) :
    import numpy as np
    user_1 = np.array(user_1)
    user_2 = np.array(user_2)
    
    return np.sqrt(np.sum((user_1 - user_2)**2))

In [65]:
distance([2,3], [4,4])

2.23606797749979

In [59]:
# 소수점 둘째자리까지만 출력
np.set_printoptions(precision = 2)


### 데이터 불러오기

In [60]:
df = pd.read_csv('./cf_ratings.csv', index_col = 'user_id')

In [61]:
df

0    1    2    3    4    5    6    7    8    9   10   11   12   13  \
user_id                                                                         
0        2.0  3.0  4.0  NaN  2.0  3.0  NaN  NaN  NaN  4.0  4.0  NaN  NaN  1.0   
1        NaN  NaN  NaN  4.0  NaN  5.0  NaN  NaN  2.0  NaN  4.0  NaN  1.0  NaN   
2        2.0  NaN  1.0  NaN  NaN  5.0  5.0  NaN  NaN  NaN  NaN  5.0  3.0  3.0   
3        NaN  3.0  5.0  NaN  NaN  NaN  4.0  3.0  NaN  5.0  3.0  NaN  4.0  NaN   
4        NaN  NaN  NaN  5.0  NaN  NaN  2.0  2.0  2.0  NaN  3.0  4.0  2.0  5.0   
5        NaN  4.0  3.0  NaN  NaN  5.0  NaN  NaN  NaN  3.0  2.0  NaN  NaN  NaN   
6        3.0  NaN  NaN  NaN  4.0  5.0  2.0  2.0  NaN  3.0  NaN  4.0  NaN  NaN   
7        NaN  5.0  1.0  4.0  NaN  NaN  NaN  3.0  1.0  NaN  1.0  NaN  NaN  4.0   
8        NaN  3.0  1.0  1.0  NaN  3.0  NaN  4.0  NaN  1.0  1.0  NaN  4.0  4.0   
9        1.0  1.0  NaN  1.0  1.0  NaN  NaN  NaN  NaN  NaN  NaN  2.0  NaN  NaN   
10       NaN  2.0  NaN  NaN  2.0  2.0  NaN  NaN  2.0  3.0  2.0  NaN  NaN  1.0   
11       3.0  NaN  NaN  5.0  4.0  NaN  NaN  4.0  5.0  3.0  NaN  1.0  2.0  1.0   
12       2.0  NaN  5.0  NaN  5.0  4.0  NaN  NaN  NaN  NaN  NaN  2.0  3.0  NaN   
13       NaN  2.0  1.0  NaN  NaN  NaN  4.0  NaN  1.0  NaN  5.0  5.0  4.0  3.0   
14       NaN  3.0  5.0  NaN  NaN  NaN  2.0  5.0  3.0  NaN  3.0  3.0  NaN  4.0   
15       NaN  NaN  2.0  5.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  NaN   
16       NaN  5.0  NaN  5.0  3.0  NaN  NaN  3.0  2.0  4.0  2.0  NaN  4.0  4.0   
17       4.0  NaN  1.0  NaN  NaN  5.0  2.0  NaN  5.0  NaN  NaN  4.0  NaN  2.0   
18       NaN  NaN  4.0  NaN  1.0  4.0  NaN  4.0  2.0  1.0  NaN  NaN  NaN  NaN   
19       2.0  NaN  NaN  2.0  5.0  NaN  2.0  NaN  2.0  1.0  NaN  NaN  5.0  2.0   

          14   15   16   17   18   19  
user_id                                
0        NaN  NaN  2.0  5.0  2.0  NaN  
1        NaN  NaN  NaN  5.0  NaN  NaN  
2        NaN  3.0  3.0  4.0  NaN  NaN  
3        NaN  2.0  NaN  NaN  NaN  2.0  
4        4.0  NaN  NaN  NaN  4.0  2.0  
5        1.0  NaN  4.0  3.0  NaN  5.0  
6        2.0  4.0  NaN  NaN  NaN  1.0  
7        NaN  NaN  2.0  NaN  NaN  4.0  
8        2.0  NaN  NaN  5.0  3.0  NaN  
9        1.0  NaN  NaN  NaN  4.0  NaN  
10       4.0  5.0  3.0  NaN  3.0  3.0  
11       1.0  NaN  NaN  NaN  4.0  NaN  
12       4.0  NaN  NaN  NaN  NaN  3.0  
13       5.0  NaN  NaN  5.0  5.0  4.0  
14       NaN  4.0  NaN  1.0  NaN  NaN  
15       NaN  NaN  3.0  1.0  5.0  2.0  
16       5.0  4.0  2.0  NaN  1.0  3.0  
17       3.0  NaN  NaN  NaN  NaN  5.0  
18       2.0  1.0  1.0  NaN  3.0  5.0  
19       2.0  3.0  NaN  NaN  1.0  2.0

### 함수 정의

In [62]:
def distance(user_1, user_2) :
    import numpy as np
    user_1 = np.array(user_1)
    user_2 = np.array(user_2)
    
    return np.sqrt(np.sum((user_1 - user_2)**2))

# movie_id 번째 영화를 평가하지 않은 사용자 미리 제외하는 함수 생성

def filter_users_without_movie(rating_data, movie_id) :
    return rating_data[~np.isnan(rating_data[:, movie_id])] 

In [63]:
# 평점 데이터의 빈 값을 사용자(유저) 평균 값 채우는 함수 생성

def fill_nan_with_user_mean(rating_data) :
    filled_data = np.copy(rating_data)
    
    # 사용자(유저)의ㅡ 평균 평점 계산
    row_mean = np.nanmean(filled_data, axis = 1)
    
    # 비어있는 인덱스 구하기
    inds = np.where(np.isnan(filled_data))
    
    # 빈 인덱스를 유저 평점으로 채우기
    filled_data[inds] = np.take(row_mean, inds[0])
    
    return filled_data
    

In [64]:
# user_id에 해당하는 사용자(유저) 이웃을 찾아주는 함수
def get_k_neighbors(user_id, rating_data, k) :
    distance_data = np.copy(rating_data)
    
    # 마지막에 거리 데이터를 담을 열 추가
    distance_data = np.append(distance_data, np.zeros((distance_data.shape[0], 1)), axis = 1)
    
    for i in range(len(distance_data)) :
        row = distance_data[i]
        
        if i == user_id :
            row[-1] = np.inf
        
        else : 
            row[-1] = distance(distance_data[user_id][:-1], row[:-1])
            
    # 데이터를 거리 열 기준 정렬
    distance_data[np.argsort(distance_data[:, -1])]
    
    # 가장 가까운 k 개의 행만 리턴한다
    # 마지막(거리) 열은 제외한다
    
    return distance_data[:k, :-1]

### fill_nan_with_user_mean 함수 뜯어보기

In [65]:
rating_data = filter_users_without_movie(df.values , 3)
rating_data

array([[nan, nan, nan,  4., nan,  5., nan, nan,  2., nan,  4., nan,  1.,
        nan, nan, nan, nan,  5., nan, nan],
       [nan, nan, nan,  5., nan, nan,  2.,  2.,  2., nan,  3.,  4.,  2.,
         5.,  4., nan, nan, nan,  4.,  2.],
       [nan,  5.,  1.,  4., nan, nan, nan,  3.,  1., nan,  1., nan, nan,
         4., nan, nan,  2., nan, nan,  4.],
       [nan,  3.,  1.,  1., nan,  3., nan,  4., nan,  1.,  1., nan,  4.,
         4.,  2., nan, nan,  5.,  3., nan],
       [ 1.,  1., nan,  1.,  1., nan, nan, nan, nan, nan, nan,  2., nan,
        nan,  1., nan, nan, nan,  4., nan],
       [ 3., nan, nan,  5.,  4., nan, nan,  4.,  5.,  3., nan,  1.,  2.,
         1.,  1., nan, nan, nan,  4., nan],
       [nan, nan,  2.,  5., nan, nan, nan, nan, nan, nan, nan, nan,  1.,
        nan, nan, nan,  3.,  1.,  5.,  2.],
       [nan,  5., nan,  5.,  3., nan, nan,  3.,  2.,  4.,  2., nan,  4.,
         4.,  5.,  4.,  2., nan,  1.,  3.],
       [ 2., nan, nan,  2.,  5., nan,  2., nan,  2.,  1., nan, n

In [66]:
filled_data = rating_data.copy()
row_mean = np.nanmean(filled_data, axis = 1)
row_mean

array([3.5 , 3.18, 2.78, 2.67, 1.57, 3.  , 2.71, 3.36, 2.42])

In [67]:
inds = np.where(np.isnan(filled_data))
inds

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4,
        4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8,
        8, 8, 8], dtype=int64),
 array([ 0,  1,  2,  4,  6,  7,  9, 11, 13, 14, 15, 16, 18, 19,  0,  1,  2,
         4,  5,  9, 15, 16, 17,  0,  4,  5,  6,  9, 11, 12, 14, 15, 17, 18,
         0,  4,  6,  8, 11, 15, 16, 19,  2,  5,  6,  7,  8,  9, 10, 12, 13,
        15, 16, 17, 19,  1,  2,  5,  6, 10, 15, 16, 17, 19,  0,  1,  4,  5,
         6,  7,  8,  9, 10, 11, 13, 14, 15,  0,  2,  5,  6, 11, 17,  1,  2,
         5,  7, 10, 11, 16, 17], dtype=int64))

In [68]:
filled_data[inds]

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [69]:
np.take(row_mean, inds[0])

array([3.5 , 3.5 , 3.5 , 3.5 , 3.5 , 3.5 , 3.5 , 3.5 , 3.5 , 3.5 , 3.5 ,
       3.5 , 3.5 , 3.5 , 3.18, 3.18, 3.18, 3.18, 3.18, 3.18, 3.18, 3.18,
       3.18, 2.78, 2.78, 2.78, 2.78, 2.78, 2.78, 2.78, 2.78, 2.78, 2.78,
       2.78, 2.67, 2.67, 2.67, 2.67, 2.67, 2.67, 2.67, 2.67, 1.57, 1.57,
       1.57, 1.57, 1.57, 1.57, 1.57, 1.57, 1.57, 1.57, 1.57, 1.57, 1.57,
       3.  , 3.  , 3.  , 3.  , 3.  , 3.  , 3.  , 3.  , 3.  , 2.71, 2.71,
       2.71, 2.71, 2.71, 2.71, 2.71, 2.71, 2.71, 2.71, 2.71, 2.71, 2.71,
       3.36, 3.36, 3.36, 3.36, 3.36, 3.36, 2.42, 2.42, 2.42, 2.42, 2.42,
       2.42, 2.42, 2.42])

### 코드 실행

In [71]:
# 실행 코드
# 영화 3을 본 유저들 중, 유저 0과 비슷한 유저를 5명 찾기
rating_data = df.values


# 3 번째 영화를 보지 않은 유저를 데이터에서 미리 제외시킨다
rating_data = filter_users_without_movie(rating_data, 3)

# nan 값 채우기
rating_data = fill_nan_with_user_mean(rating_data)
rating_data


array([[3.5 , 3.5 , 3.5 , 4.  , 3.5 , 5.  , 3.5 , 3.5 , 2.  , 3.5 , 4.  ,
        3.5 , 1.  , 3.5 , 3.5 , 3.5 , 3.5 , 5.  , 3.5 , 3.5 ],
       [3.18, 3.18, 3.18, 5.  , 3.18, 3.18, 2.  , 2.  , 2.  , 3.18, 3.  ,
        4.  , 2.  , 5.  , 4.  , 3.18, 3.18, 3.18, 4.  , 2.  ],
       [2.78, 5.  , 1.  , 4.  , 2.78, 2.78, 2.78, 3.  , 1.  , 2.78, 1.  ,
        2.78, 2.78, 4.  , 2.78, 2.78, 2.  , 2.78, 2.78, 4.  ],
       [2.67, 3.  , 1.  , 1.  , 2.67, 3.  , 2.67, 4.  , 2.67, 1.  , 1.  ,
        2.67, 4.  , 4.  , 2.  , 2.67, 2.67, 5.  , 3.  , 2.67],
       [1.  , 1.  , 1.57, 1.  , 1.  , 1.57, 1.57, 1.57, 1.57, 1.57, 1.57,
        2.  , 1.57, 1.57, 1.  , 1.57, 1.57, 1.57, 4.  , 1.57],
       [3.  , 3.  , 3.  , 5.  , 4.  , 3.  , 3.  , 4.  , 5.  , 3.  , 3.  ,
        1.  , 2.  , 1.  , 1.  , 3.  , 3.  , 3.  , 4.  , 3.  ],
       [2.71, 2.71, 2.  , 5.  , 2.71, 2.71, 2.71, 2.71, 2.71, 2.71, 2.71,
        2.71, 1.  , 2.71, 2.71, 2.71, 3.  , 1.  , 5.  , 2.  ],
       [3.36, 5.  , 3.36, 5.  , 3.  , 3.3

In [72]:
# 유저 0과 비슷한 유저 5명 찾기
get_k_neighbors(0, rating_data, 5)

array([[3.5 , 3.5 , 3.5 , 4.  , 3.5 , 5.  , 3.5 , 3.5 , 2.  , 3.5 , 4.  ,
        3.5 , 1.  , 3.5 , 3.5 , 3.5 , 3.5 , 5.  , 3.5 , 3.5 ],
       [3.18, 3.18, 3.18, 5.  , 3.18, 3.18, 2.  , 2.  , 2.  , 3.18, 3.  ,
        4.  , 2.  , 5.  , 4.  , 3.18, 3.18, 3.18, 4.  , 2.  ],
       [2.78, 5.  , 1.  , 4.  , 2.78, 2.78, 2.78, 3.  , 1.  , 2.78, 1.  ,
        2.78, 2.78, 4.  , 2.78, 2.78, 2.  , 2.78, 2.78, 4.  ],
       [2.67, 3.  , 1.  , 1.  , 2.67, 3.  , 2.67, 4.  , 2.67, 1.  , 1.  ,
        2.67, 4.  , 4.  , 2.  , 2.67, 2.67, 5.  , 3.  , 2.67],
       [1.  , 1.  , 1.57, 1.  , 1.  , 1.57, 1.57, 1.57, 1.57, 1.57, 1.57,
        2.  , 1.57, 1.57, 1.  , 1.57, 1.57, 1.57, 4.  , 1.57]])