In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.rand(3,5)

array([[0.01095275, 0.53219066, 0.3995917 , 0.72436091, 0.87579268],
       [0.09608776, 0.35513606, 0.70137463, 0.10320652, 0.40212837],
       [0.41637048, 0.25319846, 0.93993722, 0.9242628 , 0.15638162]])

In [8]:
random_mat = np.random.rand(3,5)
random_mat

array([[0.85866544, 0.64824059, 0.7552966 , 0.28645104, 0.27317526],
       [0.84141481, 0.06412637, 0.42201202, 0.24621088, 0.94384053],
       [0.45199111, 0.67791677, 0.89862851, 0.53719943, 0.24037286]])

In [9]:
np.random.seed(32)

# 임의로 유저 취향과 상품 속성 행렬 생성하는 함수

def initialize(R, num_features) :
    # 유저 취향 : 유저 데이터 개수 * 속성개수차원(k) 임의 행렬(random) >> 변수 theta 저장
    # 상품속성 : 속성개수차원(k) 임의행렬(random) * item(영화) 데이터 개수 차원(random) >> 변수 X 저장
    num_users, num_items = R.shape
    
    Theta = np.random.rand(num_users, num_features)
    X = np.random.rand(num_features, num_items)
    
    return Theta, X
    

In [10]:
# 실제 값 행렬

R = np.array([
    [3,4,1,np.nan,1,2],
    [4,4,3,np.nan,5,3],
    [2,3,np.nan,1,3,4],
    [1,3,2,4,2,2],
    [1,2,np.nan,2,2,4]
])

In [11]:
Theta, X = initialize(R, 2)
Theta

array([[0.85888927, 0.37271115],
       [0.55512878, 0.95565655],
       [0.7366696 , 0.81620514],
       [0.10108656, 0.92848807],
       [0.60910917, 0.59655344]])

In [12]:
X

array([[0.09178413, 0.34518624, 0.66275252, 0.44171349, 0.55148779,
        0.70371249],
       [0.58940123, 0.04993276, 0.56179184, 0.76635847, 0.91090833,
        0.09290995]])