# 모델을 클래스로 구현하기

단순 선형 회귀 모델은 쉽게 구현하면 다음과 같습니다.



```
# 모델을 선언 및 초기화. 단순 선형 회귀이므로 input_dim=1, output_dim=1.
model = nn.Linear(1,1)
```

이를 클래스로 구현하면 다음과 같습니다.

```
class LinearRegressionModel(nn.Module): # torch.nn.Module을 상속받는 파이썬 클래스
    def __init__(self): #
        super().__init__()
        self.linear = nn.Linear(1, 1) # 단순 선형 회귀이므로 input_dim=1, output_dim=1.

    def forward(self, x):
        return self.linear(x)
```

```
model = LinearRegressionModel()
```

위와 같은 클래스를 사용한 모델 구현 형식은 대부분의 파이토치 구현체에서 사용하고 있는 방식으로 반드시 숙지할 필요가 있습니다.

클래스(class) 형태의 모델은 nn.Module 을 상속받습니다. 그리고 __init__()에서 모델의 구조와 동작을 정의하는 생성자를 정의합니다. 이는 파이썬에서 객체가 갖는 속성값을 초기화하는 역할로, 객체가 생성될 때 자동으호 호출됩니다. super() 함수를 부르면 여기서 만든 클래스는 nn.Module 클래스의 속성들을 가지고 초기화 됩니다. foward() 함수는 모델이 학습데이터를 입력받아서 forward 연산을 진행시키는 함수입니다. 이 forward() 함수는 model 객체를 데이터와 함께 호출하면 자동으로 실행이됩니다. 예를 들어 model이란 이름의 객체를 생성 후, model(입력 데이터)와 같은 형식으로 객체를 호출하면 자동으로 forward 연산이 수행됩니다.

$H(x)$ 식에 입력 $x$로부터 예측된 $y$를 얻는 것을 forward 연산이라고 합니다.  

# 단순선형회귀 클래스를 이용한 구현

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
torch.manual_seed(1)

In [3]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [4]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1)

    def forward(self, x):
        return self.linear(x)

In [5]:
model = LinearRegressionModel()

In [6]:
# optimizer 설정. 경사 하강법 SGD를 사용하고 learning rate를 의미하는 lr은 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=0.01) 

In [7]:
# 전체 훈련 데이터에 대해 경사 하강법을 2,000회 반복
nb_epochs = 2000
for epoch in range(1, nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)

    # 파이토치에서 제공하는 평균 제곱 오차 함수
    cost = F.mse_loss(prediction, y_train) 

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward() # backward 연산
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch  100/2000 Cost: 0.002804
Epoch  200/2000 Cost: 0.001733
Epoch  300/2000 Cost: 0.001071
Epoch  400/2000 Cost: 0.000662
Epoch  500/2000 Cost: 0.000409
Epoch  600/2000 Cost: 0.000253
Epoch  700/2000 Cost: 0.000156
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000060
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [8]:
input = torch.FloatTensor([[1], [2], [3]])

output = model(input)
print(output)

tensor([[2.0008],
        [4.0002],
        [5.9995]], grad_fn=<AddmmBackward0>)


In [9]:
input = torch.FloatTensor([[2], [4], [6]])

output = model(input)
print(output)

tensor([[ 4.0002],
        [ 7.9989],
        [11.9976]], grad_fn=<AddmmBackward0>)


# 다중선형회귀 클래스를 이용한 구현

In [10]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [11]:
torch.manual_seed(1)

In [12]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [13]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1) # 다중 선형 회귀이므로 input_dim=3, output_dim=1.

    def forward(self, x):
        return self.linear(x)

In [14]:
model = MultivariateLinearRegressionModel()

In [15]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) 

In [16]:
nb_epochs = 2000
for epoch in range(1, nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)
    # model(x_train)은 model.forward(x_train)와 동일함.

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch  100/2000 Cost: 0.226011
Epoch  200/2000 Cost: 0.223930
Epoch  300/2000 Cost: 0.221953
Epoch  400/2000 Cost: 0.220074
Epoch  500/2000 Cost: 0.218288
Epoch  600/2000 Cost: 0.216593
Epoch  700/2000 Cost: 0.214968
Epoch  800/2000 Cost: 0.213431
Epoch  900/2000 Cost: 0.211972
Epoch 1000/2000 Cost: 0.210572
Epoch 1100/2000 Cost: 0.209247
Epoch 1200/2000 Cost: 0.207987
Epoch 1300/2000 Cost: 0.206780
Epoch 1400/2000 Cost: 0.205629
Epoch 1500/2000 Cost: 0.204536
Epoch 1600/2000 Cost: 0.203490
Epoch 1700/2000 Cost: 0.202495
Epoch 1800/2000 Cost: 0.201550
Epoch 1900/2000 Cost: 0.200642
Epoch 2000/2000 Cost: 0.199783


In [17]:
input = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])

output = model(input)
print(output)

tensor([[151.2305],
        [184.8005],
        [180.5203],
        [196.3101],
        [141.9926]], grad_fn=<AddmmBackward0>)


# 로지스틱 회귀 클래스를 이용한 구현

In [18]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [19]:
torch.manual_seed(1)

In [20]:
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]

x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [21]:
class BinaryClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        # nn.Linear에서 앞의 인자는 input의 크기, 뒤의 인자는 output의 크기를 의미한다.
        self.linear = nn.Linear(2, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        return self.sigmoid(self.linear(x))

In [22]:
model = BinaryClassifier()

In [23]:
# optimizer 설정
optimizer = optim.SGD(model.parameters(), lr=1)

nb_epochs = 1000
for epoch in range(1, nb_epochs + 1):

    # H(x) 계산
    hypothesis = model(x_train)

    # cost 계산
    cost = F.binary_cross_entropy(hypothesis, y_train)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 20번마다 로그 출력
    if epoch % 20 == 0:
      prediction = hypothesis >= torch.FloatTensor([0.5]) # 예측값이 0.5를 넘으면 True로 간주
      correct_prediction = prediction.float() == y_train # 실제값과 일치하는 경우만 True로 간주
      accuracy = correct_prediction.sum().item() / len(correct_prediction) # 정확도를 계산
      print('Epoch {:4d}/{} Cost: {:.6f} Accuracy {:2.2f}%'.format( # 각 에포크마다 정확도를 출력
          epoch, nb_epochs, cost.item(), accuracy * 100,
      ))

Epoch   20/1000 Cost: 0.596826 Accuracy 83.33%
Epoch   40/1000 Cost: 0.405330 Accuracy 83.33%
Epoch   60/1000 Cost: 0.249201 Accuracy 83.33%
Epoch   80/1000 Cost: 0.159492 Accuracy 100.00%
Epoch  100/1000 Cost: 0.135187 Accuracy 100.00%
Epoch  120/1000 Cost: 0.119004 Accuracy 100.00%
Epoch  140/1000 Cost: 0.106340 Accuracy 100.00%
Epoch  160/1000 Cost: 0.096161 Accuracy 100.00%
Epoch  180/1000 Cost: 0.087799 Accuracy 100.00%
Epoch  200/1000 Cost: 0.080806 Accuracy 100.00%
Epoch  220/1000 Cost: 0.074868 Accuracy 100.00%
Epoch  240/1000 Cost: 0.069763 Accuracy 100.00%
Epoch  260/1000 Cost: 0.065325 Accuracy 100.00%
Epoch  280/1000 Cost: 0.061429 Accuracy 100.00%
Epoch  300/1000 Cost: 0.057982 Accuracy 100.00%
Epoch  320/1000 Cost: 0.054909 Accuracy 100.00%
Epoch  340/1000 Cost: 0.052152 Accuracy 100.00%
Epoch  360/1000 Cost: 0.049664 Accuracy 100.00%
Epoch  380/1000 Cost: 0.047407 Accuracy 100.00%
Epoch  400/1000 Cost: 0.045350 Accuracy 100.00%
Epoch  420/1000 Cost: 0.043466 Accuracy 100

In [24]:
input = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
input_tensor = torch.Tensor(input)

output = model(input_tensor)
prediction = output >= torch.FloatTensor([0.5])
print(prediction)

tensor([[False],
        [False],
        [False],
        [ True],
        [ True],
        [ True]])


In [25]:
y_pred = np.zeros(output.shape)
y_pred[np.where(output >= 0.5)] = 1
print(y_pred)

[[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]]


# 클래스로 소프트맥스 회귀 구현하기

In [26]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [27]:
torch.manual_seed(1)

In [28]:
x_train = [[1, 2, 1, 1],
           [2, 1, 3, 2],
           [3, 1, 3, 4],
           [4, 1, 5, 5],
           [1, 7, 5, 5],
           [1, 2, 5, 6],
           [1, 6, 6, 6],
           [1, 7, 7, 7]]
y_train = [2, 2, 2, 1, 1, 1, 0, 0]

x_train = torch.FloatTensor(x_train)
y_train = torch.LongTensor(y_train)

In [29]:
class SoftmaxClassifierModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(4, 3) # Input이 4, Output이 3!

    def forward(self, x):
        return self.linear(x)

In [30]:
model = SoftmaxClassifierModel()

In [31]:
# optimizer 설정
optimizer = optim.SGD(model.parameters(), lr=0.1)

nb_epochs = 1000
for epoch in range(1, nb_epochs + 1):

    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.cross_entropy(prediction, y_train)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 20번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

Epoch  100/1000 Cost: 0.714870
Epoch  200/1000 Cost: 0.633744
Epoch  300/1000 Cost: 0.576285
Epoch  400/1000 Cost: 0.525854
Epoch  500/1000 Cost: 0.478306
Epoch  600/1000 Cost: 0.432054
Epoch  700/1000 Cost: 0.386326
Epoch  800/1000 Cost: 0.340779
Epoch  900/1000 Cost: 0.295738
Epoch 1000/1000 Cost: 0.255139


In [32]:
input = [[1, 2, 1, 1],
           [2, 1, 3, 2],
           [3, 1, 3, 4],
           [4, 1, 5, 5],
           [1, 7, 5, 5],
           [1, 2, 5, 6],
           [1, 6, 6, 6],
           [1, 7, 7, 7]]
input_tensor = torch.Tensor(input)

output = model(input_tensor)
print(output)

tensor([[-4.2606, -0.1446,  4.7014],
        [-2.8552,  0.7746,  2.6069],
        [-6.9495,  3.7046,  4.6549],
        [-5.8910,  4.4509,  3.0981],
        [ 1.3698,  2.1889, -1.3623],
        [ 2.6140,  4.3142, -4.3078],
        [ 3.5578,  3.1613, -4.0880],
        [ 5.0522,  3.7879, -5.7384]], grad_fn=<AddmmBackward0>)


In [33]:
for sample in output:
  print(torch.argmax(sample))
# softmax 결과 확률값이 가장 큰 값(예측한 클래스) 결과 출력

tensor(2)
tensor(2)
tensor(2)
tensor(1)
tensor(1)
tensor(1)
tensor(0)
tensor(0)


In [34]:
for sample in output:
  print(np.argmax(sample.detach().cpu().numpy()))

2
2
2
1
1
1
0
0
