배열(ndarray, n dimension array)

- 리스트(list) 
    - Linked list 구조(불연속), 동작속도가 느림
    - comma(,)로 요소 구별, 서로 다른 자료형 사용 가능
- 배열(ndarray)
    - 연속된 메모리 구조, 동작속도가 빠름
    - comma(,) 사용하지 않고 공백으로 요소 구별

배열(array) 만들기

In [2]:
import numpy as np

# 0부터 4까지 연속적인 숫자가 들어 있는 배열을 만들어 보기

arr = np.array(range(5))
print(arr)

[0 1 2 3 4]


In [5]:
li = [1,2,3,4,5]
print(li)

[1, 2, 3, 4, 5]


In [7]:
# list

list1 = [0,2,3,4,5,'kim']
print(list1) # comma있다
print(type(list1))

[0, 2, 3, 4, 5, 'kim']
<class 'list'>


In [9]:
a = np.array([0,1,2,3,4,5])
print(a)
print(type(a)) # ndarray >> 넘파이 배열
print(a.dtype) # 요소의 자료형

[0 1 2 3 4 5]
<class 'numpy.ndarray'>
int32


In [10]:
# numpy dtype 객체의 종류
# 대소문자 모두 사용 가능

np.sctypeDict.keys()

dict_keys(['?', 0, 'byte', 'b', 1, 'ubyte', 'B', 2, 'short', 'h', 3, 'ushort', 'H', 4, 'i', 5, 'uint', 'I', 6, 'intp', 'p', 9, 'uintp', 'P', 10, 'long', 'l', 7, 'L', 8, 'longlong', 'q', 'ulonglong', 'Q', 'half', 'e', 23, 'f', 11, 'double', 'd', 12, 'longdouble', 'g', 13, 'cfloat', 'F', 14, 'cdouble', 'D', 15, 'clongdouble', 'G', 16, 'O', 17, 'S', 18, 'unicode', 'U', 19, 'void', 'V', 20, 'M', 21, 'm', 22, 'bool8', 'b1', 'int64', 'i8', 'uint64', 'u8', 'float16', 'f2', 'float32', 'f4', 'float64', 'f8', 'complex64', 'c8', 'complex128', 'c16', 'object0', 'bytes0', 'str0', 'void0', 'datetime64', 'M8', 'timedelta64', 'm8', 'Bytes0', 'Datetime64', 'Str0', 'Uint64', 'int32', 'i4', 'uint32', 'u4', 'int16', 'i2', 'uint16', 'u2', 'int8', 'i1', 'uint8', 'u1', 'complex_', 'int0', 'uint0', 'single', 'csingle', 'singlecomplex', 'float_', 'intc', 'uintc', 'int_', 'longfloat', 'clongfloat', 'longcomplex', 'bool_', 'bytes_', 'string_', 'str_', 'unicode_', 'object_', 'int', 'float', 'complex', 'bool', 'ob

In [11]:
# int와 float >> float

a = np.array([0,1,2,3,4,5])

print(a) # comma(,) 가 없네
print(type(a))
print(a.dtype) # dtype : data type 자료유형

[0 1 2 3 4 5]
<class 'numpy.ndarray'>
int32


In [12]:
a = np.array([0,1,2.,3,4,5])
 
print(a) # comma(,) 가 없네
print(type(a))
print(a.dtype) # dtype : data type 자료유형

[0. 1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>
float64


In [14]:
# int와 float와 str >> unicode

a = np.array([0,1,2,3,4,5,'kim'])
print(a)
print(type(a))
print(a.dtype)
# <U11 : 
# - < : 리틀엔디언, U : 유니코드, 11 : 최대문자 11byte

['0' '1' '2' '3' '4' '5' 'kim']
<class 'numpy.ndarray'>
<U11


유니코드 인코딩방식

- (1) euc-kr, cp949(MS949) : 완성형, 한글 2byte, 영문 1byte >> windows
- (2) utf-8 : 조합형, 한글 3byte, 영문 1byte >> Linux

In [24]:
# 배열의 데이터 타입 변환 : astype()

a1 = np.array(['1.234','3.125','4.435','5','7'])
print(a1, a1.dtype) # 문자

['1.234' '3.125' '4.435' '5' '7'] <U5


In [25]:
a2 = a1.astype('float32')
print(a2, a2.dtype)

[1.234 3.125 4.435 5.    7.   ] float32


In [26]:
a3 = a2.astype('int32')
print(a3, a3.dtype)

[1 3 4 5 7] int32


차원(dimension, Rank)과 shape

- 차원(dimension, Rank) : 1,2,3 차원 ... n차원, 첫 데이터까지의 대괄호 개수
- shape : 차원의 요소의 수, 튜플 형식

- 1차원 shape(x,)
- 2차원 shape(x, y) >> 행렬(matrix)
- 3차원 shape(x, y, z) >> (면, 행, 열)

In [27]:
print('1차원 array')
arr = np.array(range(10))
print(arr)

1차원 array
[0 1 2 3 4 5 6 7 8 9]


In [28]:
print(type(arr))

<class 'numpy.ndarray'>


In [29]:
print(arr.ndim)

1


In [30]:
arr.shape

(10,)

In [31]:
arr.size

10

In [32]:
arr.dtype # 데이터 유형 >> int : 정수

dtype('int32')

In [33]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
print(arr[5])

5


In [35]:
print(arr[3:6])

[3 4 5]


In [37]:
# 1차원 배열의 shape

a = np.arange(12)
print(a, type(a), a.dtype)
print(a.shape) # 1차원

[ 0  1  2  3  4  5  6  7  8  9 10 11] <class 'numpy.ndarray'> int32
(12,)


In [39]:
t = a.shape
print(type(t))
print(a.shape[0])

<class 'tuple'>
12


In [41]:
a2 = np.arange(2,10)

print(a2, type(a2))
print(a2.shape)

[2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
(8,)


In [43]:
a3 = np.arange(0,16,2)
print(a3, type(a3))
print(a3.shape)

[ 0  2  4  6  8 10 12 14] <class 'numpy.ndarray'>
(8,)


In [50]:
print('2차원 array')

# 1부터 15까지 들어 있는 (3, 5) 배열 생성
mat = np.array(range(1,16)).reshape(3,5)

print(mat)

2차원 array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [51]:
mat = np.array(range(1,16))
mat.shape = 3,5

In [52]:
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [54]:
# mat 자료형 출력해 보세요
print(type(mat))

<class 'numpy.ndarray'>


In [55]:
# mat 차원 출력
print(mat.ndim)

2


In [56]:
# mat 모양 출력
print(mat.shape)

(3, 5)


In [58]:
# mat 크기 출력
print(mat.size)

15


In [59]:
# mat 데이터 유형 출력
print(mat.dtype)

int32


In [60]:
# mat dtype >> str 변경
print(mat.astype('str'))

[['1' '2' '3' '4' '5']
 ['6' '7' '8' '9' '10']
 ['11' '12' '13' '14' '15']]


In [61]:
# 행렬 (2,3) 인덱스의 요소 출력

print(mat[2,3])

14


In [62]:
# matrix의 행은 인덱스 0부터 인덱스 1까지
# 열은 인덱스 1부터 3까지 출력 해보세요
print(mat[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [63]:
# 2차원 배열의 shape
# 행(row) axis = 0, 열(column) aixs = 1

m = np.array([[0,1,2],
              [0,1,2]])

print(m)
print(m.shape)
print(m.shape[0], m.shape[1])
# 2개의 record, 3개의 feature

[[0 1 2]
 [0 1 2]]
(2, 3)
2 3


In [68]:
# 3차원 배열의 shape (면, 행, 열)
m = np.array([[[0,1,2],
               [3,4,5]],
              [[0,1,2],
               [3,4,5]]])

In [69]:
print(m)
print(m.shape)
print(m.shape[0], m.shape[1], m.shape[2])

[[[0 1 2]
  [3 4 5]]

 [[0 1 2]
  [3 4 5]]]
(2, 2, 3)
2 2 3


배열의 shape 바꾸기 : reshape() 함수

In [70]:
m1 = np.arange(12)
print(m1, m1.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)


In [72]:
m2 = m1.reshape(3, 4)

In [73]:
print(m2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [74]:
print(m2.shape)

(3, 4)


In [77]:
m2 = m1.reshape(4, -1)

In [78]:
print(m2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [79]:
print(m2.shape)

(4, 3)


In [81]:
m3 = m1.reshape(2,2,3)

In [82]:
print(m3)
print(m3.shape)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(2, 2, 3)


In [83]:
m1.reshape(3,2,1,2)

array([[[[ 0,  1]],

        [[ 2,  3]]],


       [[[ 4,  5]],

        [[ 6,  7]]],


       [[[ 8,  9]],

        [[10, 11]]]])

In [84]:
m1 = np.arange(12)
m1.reshape(-1, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [85]:
m1.reshape(-1,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

배열의 인덱싱과 슬라이싱

In [87]:
x = np.arange(7)
print(x)

[0 1 2 3 4 5 6]


In [88]:
print(x[3])

3


In [89]:
print(x[1:4])

[1 2 3]


In [90]:
print(x[x<3])

[0 1 2]


In [91]:
print(x[x%2 == 0])

[0 2 4 6]


In [93]:
# method chaining 활용

m = np.arange(1,13,2).reshape(2,3)
print(m)

[[ 1  3  5]
 [ 7  9 11]]


In [94]:
m[0,1] # 원소 3추출

3

In [96]:
m[1:,1:]

array([[ 9, 11]])

In [97]:
m2 = np.arange(1,13).reshape(3,4)
print(m2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [98]:
# indexing 이용, 값 2 추출

m2[0,1]

2

In [101]:
# slicing 이용, 9 10 추출
m2[2:,:2]

array([[ 9, 10]])

In [103]:
# boolean indexing 통해 5보다 작은 수 찾아 출력
m2[m2<5]

array([1, 2, 3, 4])

In [105]:
# fancy index 두번째 행만 추출해서 출력

m2[[1]]

array([[5, 6, 7, 8]])

In [106]:
# 1차원 배열 인덱싱과 슬라이싱 : 리스트(list) 와 동일한 방법

d = np.arange(12)
print(d, d.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)


In [107]:
print(d[0],d[-1])

0 11


In [108]:
print(d[2:8], d[:], d[:-1])

[2 3 4 5 6 7] [ 0  1  2  3  4  5  6  7  8  9 10 11] [ 0  1  2  3  4  5  6  7  8  9 10]


In [110]:
print(d[::2], d[::-1])

[ 0  2  4  6  8 10] [11 10  9  8  7  6  5  4  3  2  1  0]


In [111]:
d[0] = 10
print(d)

[10  1  2  3  4  5  6  7  8  9 10 11]


In [113]:
# 2차원 배열의 인덱싱과 슬라이싱

d = np.arange(12).reshape(3,4)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [115]:
print(d[0][0])
print(d[0,0])
print(d[2,1])

0
0
9


In [116]:
# 슬라이싱

print(d[0])

[0 1 2 3]


In [117]:
print(d[0,:])

[0 1 2 3]


In [118]:
print(d[:,:-1])

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]


In [119]:
print(d[::2, ::2])

[[ 0  2]
 [ 8 10]]


In [120]:
d[0] = 20 # 0번째 행의 모든 요소를 20으로 변경
print(d)

[[20 20 20 20]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [121]:
d[::2, ::2] = 30 # 슬라이싱 된 요소 전체를 한번에 변경 가능
print(d)

[[30 20 30 20]
 [ 4  5  6  7]
 [30  9 30 11]]


In [122]:
d[:,:] = -1 # 전체를 한번에 변경 ㅠ

print(d)

[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [126]:
# 3차원 배열의 인덱싱과 슬라이싱

# data[면, 행, 열]

d = np.arange(12).reshape(2,2,3)
print(d, d.shape)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] (2, 2, 3)


In [128]:
# 인덱싱

print(d[0][0][0]) # old style

print(d[0,0,0])

print(d[0,1,2])

0
0
5


In [130]:
# 슬라이싱

print(d[:,:-1,:-1])

print(d[:, 1:, 1:])

[[[0 1]]

 [[6 7]]]
[[[ 4  5]]

 [[10 11]]]


In [133]:
print(d[:,:,-1])

[[ 2  5]
 [ 8 11]]


In [134]:
print(d[:,-1,-1])

[ 5 11]


In [137]:
# boolean indexing(매우 중요)
# 조건식을 사용한 인덱싱, 조건 검색 필터

a = np.array([1,2,3,4,5,6])

print(a)

print(a>2)

print(a[a>2]) # True(참 값)만 추출

[1 2 3 4 5 6]
[False False  True  True  True  True]
[3 4 5 6]


In [138]:
bool_idx = [False, False,  True,  True,  True,  True]
print(a[bool_idx])

[3 4 5 6]


In [139]:
print(a[a != 3])

[1 2 4 5 6]


In [140]:
print(a[(a>2)&(a<6)])

[3 4 5]


In [141]:
condition = (a%2) == 0
print(a[condition])

[2 4 6]


In [142]:
print(a[a<a.mean()])

[1 2 3]


In [143]:
condition = a < a.mean()
print(a[condition])

[1 2 3]


In [ ]:
# fancy indexing
# 리스트나 배열로 임의의 집합을 지정한 인덱싱
# 멋대로 내키는 대로 인덱싱

In [144]:
# 1차원 배열의 fancy indexing

a = np.arange(1,7)
print(a, a.shape)

[1 2 3 4 5 6] (6,)


In [145]:
print(a[[1,3,5,2,3,1]])

[2 4 6 3 4 2]


In [149]:
print(a[[0,-1,-3,-2]])

[1 6 4 5]


In [159]:
# 2차원 배열의 fancy indexing

a = np.arange(10,100, 10).reshape(3,3)
print(a, a.shape)

print(a[[0,2],[0,1]])
# 행과 열이 서로 match a[0,0], a[2,1]
print(a[[0,2], :2])

[[10 20 30]
 [40 50 60]
 [70 80 90]] (3, 3)
[10 80]
[[10 20]
 [70 80]]


배열의 형상 다루기

- (매우 중요) reshape(), 편평화 flatten(), 전치(transpose())
- flatten() : 다차원 배열 >> 1차원 배열로 변환

In [170]:
d = np.arange(12).reshape(3,4)

In [171]:
# transpose()
d.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [172]:
d.flat = 0
print(d, d.shape)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] (3, 4)


In [173]:
# axis(축) 사용법

a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [179]:
print(a.sum()) # 배열 전체의 합
print(a.sum(axis = None)) # 배열 전체의 합
print(a.sum(axis = 0)) # 행 단위
print(a.sum(axis = 1)) # 열 단위
print(a.sum(axis = -1)) # 마지막 축 방향의 합
print(a.mean()) # 배열 전체의 평균


66
66
[12 15 18 21]
[ 6 22 38]
[ 6 22 38]
5.5


In [180]:
# sort() 함수 : 오름차순(default)

a = np.array([9,2,8,3,1,4,5,6])
print(a, a.shape)

[9 2 8 3 1 4 5 6] (8,)


In [182]:
np.sort(a)

array([1, 2, 3, 4, 5, 6, 8, 9])

In [183]:
np.sort(a)[::-1]

array([9, 8, 6, 5, 4, 3, 2, 1])

In [185]:
# argsort() 함수 
# sort된 후 해당 값의 인덱스(idx) 반환

a = np.array([9,2,8,3,1,4,5,6])
print(a, a.shape)
print(np.sort(a))
sort_idx = np.argsort(a)
print(sort_idx)


[9 2 8 3 1 4 5 6] (8,)
[1 2 3 4 5 6 8 9]
[4 1 3 5 6 7 2 0]


In [188]:
print(a[sort_idx])

[1 2 3 4 5 6 8 9]


In [191]:
m = np.arange(1, 13).reshape(3,4)

print(m)

print(m[0,1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2


In [195]:
m[2:, :2]

array([[ 9, 10]])

m[m<5]

In [196]:
m[m<5]

array([1, 2, 3, 4])

In [197]:
m[[1]]

array([[5, 6, 7, 8]])

numpy의 method

1. np.arange(정수)
2. np.zeors(정수)
3. np.ones(정수)
4. np.sum(배열)
5. np.mean(배열)
6. np.std(배열)
7. 배열.reshape(shape)


In [199]:
arr1 = np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [200]:
arr2 = np.zeros(10)
print(arr2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [201]:
arr3 = np.ones(10)
print(arr3)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [202]:
np.sum(arr1) # arr1 배열의 전체 원소의 합

45

In [203]:
np.mean(arr1) # arr1 배열의 전체 원소의 평균

4.5

In [205]:
np.std(arr1) # arr1 배열의 전체 원소의 표준편차(평균에서 떨어진 값)

2.8722813232690143

In [206]:
arr1.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])