In [1]:
a, b = 12, 45
print(a, b)

print()

a, b = b, a
print(a, b)

12 45

45 12


In [2]:
a = [10, 20, 30, 40]

print(sum(a))

100


In [3]:
a = {0:10, 1:20, 2:30, 3:40}
print(a[0])

10


In [4]:
print(type(a))

<class 'dict'>


In [5]:
a = set(a)
a.add(4)
print(a)

{0, 1, 2, 3, 4}


In [6]:
a, b = '안녕', '세싹'

print(a)
print(b)

print(a*2+b)

안녕
세싹
안녕안녕세싹


In [18]:
import numpy as np

a = np.arange(20,36,2)

a.shape

(8,)

In [11]:
b = np.arange(20,36,2).reshape(2,4)
b

array([[20, 22, 24, 26],
       [28, 30, 32, 34]])

In [13]:
b.ndim # num of dimension

2

In [15]:
bb = b * 10 # broadcasting
bb

array([[200, 220, 240, 260],
       [280, 300, 320, 340]])

In [16]:
b[0,0] = 13
b

array([[13, 22, 24, 26],
       [28, 30, 32, 34]])

In [19]:
x = np.array([
    [0.1, 0.8, 0.1],
    [0.3, 0.1, 0.6], 
    [0.2, 0.5, 0.3],
    [0.8, 0.1, 0.1]
])


In [20]:
y = np.argmax(x)
y

# np.argmax(x)
# x 배열을 1차원으로 평면화된 배열에 대해서
# 최대값을 갖는 인덱스(idx)를 반환

1

In [22]:
z = np.array([
    [0.1, 0.8, 0.1],
    [0.3, 0.1, 0.6], 
    [0.2, 0.5, 0.3],
    [0.9, 0.1, 0.1]
])

In [24]:
y_1 = np.argmax(z)
y_1


9

In [28]:
np.argmax(z, axis = 0) # 서로 다른 행끼리(세로방향)

# np.argmax(x, axis = 0)
# 첫번째 축인 row 방향(세로방향)으로 구성되는 요소 중 최대인 인덱스를 반환

array([3, 0, 1], dtype=int64)

In [27]:
np.argmax(z, axis = 1) # 서로 다른 열끼리(가로방향)

array([1, 2, 1, 0], dtype=int64)

In [29]:
np.argmax(z, axis = -1)

array([1, 2, 1, 0], dtype=int64)